import type { CutsceneDefinition } from "./types.ts";

export const CUTSCENES: CutsceneDefinition[] = [
  {
    id: "lily_truth_broadcast",
    triggerStoryEventId: "lily-truth",
    triggerStoryChoiceId: "broadcast",
    priority: 180,
    kicker: "JUJU HOTEL · OPEN FREQUENCY",
    title: "침묵보다 위험한 첫 문장",
    body: "Lily는 복원한 문서와 실종 좌표를 낡은 송신기 앞에 펼쳤다. 호텔의 위치를 감추던 마지막 침묵이 마이크 스위치와 함께 끊겼다. 그녀가 괴물의 모방 행동과 지하 기록의 날짜를 읽어 내려가자 처음에는 빗소리뿐이었다. 송신을 마친 순간, 멀리 떨어진 수신 표시등 하나가 짧게 깜빡였다. 목소리는 아직 없었지만 누군가 이 주파수를 듣고 있었다.",
    quote: "여기는 JUJU HOTEL. 이 기록을 들은 사람이 있다면, 믿지 말고 대조해 주세요. 그리고 살아서 답해 주세요.",
    image: "/juminjung/assets/cutscenes/lily-truth-broadcast-v1.png",
    imageAlt: "릴리 포스터가 비 내리는 JUJU HOTEL 라디오실에서 해독 문서를 펼치고 낡은 마이크로 진실을 방송하며, 아날로그 수신기의 미확인 신호등이 켜지는 장면.",
  },
  {
    id: "lily_truth_archive",
    triggerStoryEventId: "lily-truth",
    triggerStoryChoiceId: "archive",
    priority: 180,
    kicker: "JUJU HOTEL · SEALED ARCHIVE",
    title: "대답이 오지 않는 금고",
    body: "Lily는 복원한 문서의 암호화 사본과 원본 필름, 테이프를 방화 보관함 안에 순서대로 눕힌 뒤 붉은 봉인을 걸었다. 기록은 사라지지 않을 것이고, 금고문이 닫히는 동안 호텔의 위치도 침묵 속에 남았다. 책상 위 마이크는 전원이 빠진 채 식어 있었고, 아날로그 수신기의 응답등도 켜지지 않았다. 괴물의 첫날을 기억하는 바깥 생존자들이 어디엔가 살아 있더라도, 그들은 이 기록을 들을 수 없고 Lily 역시 그들의 증언을 받을 수 없었다. 진실은 안전해졌지만 혼자 남았다.",
    quote: "지금 공개해서 잃는 것보다, 끝까지 보존해서 증명할 수 있는 날을 기다리겠어요.",
    image: "/juminjung/assets/cutscenes/lily-truth-archive-v1.png",
    imageAlt: "릴리 포스터가 JUJU HOTEL 지하 기록실의 강철 금고에 해독 문서와 필름, 테이프를 넣고 황동 잠금 장치를 돌리는 동안, 책상 위 낡은 마이크와 아날로그 라디오는 전원이 꺼진 채 빗속 먼 중계탑을 향해 침묵하는 장면.",
  },
  {
    id: "victor_public_trust",
    triggerStoryEventId: "victor-crown",
    triggerStoryChoiceId: "public_trust",
    priority: 170,
    kicker: "JUJU HOTEL · PUBLIC BUNKER TRUST",
    title: "좌석 번호가 사람들의 이름으로 돌아온 날",
    body: "Victor는 잠긴 가방을 열어 황동 좌석표와 벙커 열쇠를 공동 장부 앞으로 밀었다. 주민들은 그의 계약서를 믿는 대신 물과 식량 상자를 직접 세고, 피난민 명단과 빈 좌석을 같은 줄에 기록했다. 지하 철문은 더 이상 돈을 낸 사람만 아는 출구가 아니었다. Victor의 손에서 소유권은 빠져나갔지만, 그가 만든 은신처는 처음으로 폭우 속 사람들을 호텔 한곳에 몰아넣지 않고 나눠 숨길 수 있는 공공망이 되었다.",
    quote: "열쇠를 넘긴다고 숫자가 공평해지는 건 아닙니다. 그러니 모두가 직접 세십시오.",
    image: "/juminjung/assets/cutscenes/victor-public-trust-v1.png",
    imageAlt: "빅터 케인이 JUJU HOTEL 지하 기록실에서 황동 벙커 좌석표와 열쇠를 공동 장부 앞으로 내놓고, 주민들이 비축 식량과 물을 세며 피난민을 열린 철문 안으로 안내하는 장면.",
  },
  {
    id: "victor_monopoly_alliance",
    triggerStoryEventId: "victor-crown",
    triggerStoryChoiceId: "rule_market",
    priority: 170,
    kicker: "JUJU HOTEL · PRIVATE MARKET",
    title: "가격표가 문보다 먼저 닫힌 밤",
    body: "Victor는 시장길과 벙커 입구를 잇는 지도 위에서 검은 장부를 천천히 덮었다. Jack은 마지막 보급 상자에 자물쇠를 채웠고, 식량과 의약품, 연료병은 호텔 몫과 거래 몫으로 나뉘어 철제 우리 안에 들어갔다. 황동 열쇠와 좌석표는 저울 한쪽에 쌓였지만, 빗속에서 기다리는 사람들의 이름은 어느 장부에도 적히지 않았다. 호텔의 창고는 가득 찼고 시장은 조용해졌다. 그날부터 문을 여는 기준은 위험이나 필요가 아니라, Victor와 호텔이 정한 가격이 되었다.",
    quote: "구할 수 있는 수가 정해졌다면, 가격을 정하는 쪽이 살아남습니다.",
    image: "/juminjung/assets/cutscenes/victor-monopoly-alliance-v1.png",
    imageAlt: "빅터 케인이 JUJU HOTEL 프런트에서 시장길과 벙커 입구 지도를 검은 장부 아래 봉인하고, 잭이 식량과 의약품, 연료 상자를 잠그는 동안 경비가 빗속 생존자들 앞에서 철문을 닫는 장면.",
  },
  {
    id: "jack_fair_exchange",
    triggerStoryEventId: "jack-market",
    triggerStoryChoiceId: "fair_market",
    priority: 170,
    kicker: "JUJU HOTEL · OPEN EXCHANGE",
    title: "모두가 저울을 볼 수 있는 시장",
    body: "Jack은 프런트 위에 통조림과 연료병을 올린 뒤 값을 혼자 부르지 않았다. 주민 한 명이 저울을 확인하고, 다른 사람은 들어온 물자와 나간 배급표를 같은 장부에 적었다. 교환 기준은 그림 카드로 벽에 걸렸고, 다음 원정의 연료는 공개 상자에서 한 병씩만 꺼냈다. Jack에게는 이익을 숨길 구석이 줄었지만, 길에서 돌아온 물자가 누구의 몫인지 다투는 시간도 사라졌다. 폐허의 시장은 처음으로 가장 영리한 사람보다 가장 많은 눈이 지키는 곳이 되었다.",
    quote: "좋아. 내 손만 보지 말고 저울도 봐. 둘이 다르면 장부가 이기는 거야.",
    image: "/juminjung/assets/cutscenes/jack-fair-exchange-v1.png",
    imageAlt: "잭 먼로가 JUJU HOTEL 프런트의 공개 교환대에 통조림과 연료병을 올리고, 주민들이 황동 저울과 공동 장부, 그림 교환표를 함께 검토하는 장면.",
  },
  {
    id: "jack_monopoly_market",
    triggerStoryEventId: "jack-market",
    triggerStoryChoiceId: "monopoly",
    priority: 170,
    kicker: "JUJU HOTEL · PRIVATE EXCHANGE",
    title: "열쇠가 값이 된 시장",
    body: "Jack은 잠긴 물자 우리 앞에서 황동 창고 열쇠를 프런트 위에 펼쳐 놓고 검은 장부를 덮었다. 통조림과 연료병은 전보다 많아졌지만, 붉은 줄 뒤에서 차례를 기다리는 사람들은 Jack과 Victor가 나눠 준 거래 패가 없으면 저울 가까이 갈 수도 없었다. Victor는 벙커와 운송로를 잇는 지도에 새 선을 그었고, 경비는 마지막 자물쇠를 채웠다. 호텔은 굶지 않을 힘과 가격을 정할 권리를 얻었다. 대신 그날부터 필요한 사람보다 값을 치를 수 있는 사람이 먼저 문 안으로 들어왔다.",
    quote: "왕관은 필요 없어. 창고 열쇠와 가격표면 충분하지.",
    image: "/juminjung/assets/cutscenes/jack-monopoly-market-v1.png",
    imageAlt: "잭 먼로가 JUJU HOTEL 프런트에서 황동 창고 열쇠와 닫힌 장부를 차지한 채 서 있고, 빅터 케인이 벙커 운송로 지도를 확인하는 동안 경비가 가득 찬 통조림과 연료 우리를 잠그고 거래 패가 부족한 생존자들이 빗속 줄에 남는 장면.",
  },
  {
    id: "hayes_command_signed",
    triggerStoryEventId: "hayes-command",
    triggerStoryChoiceId: "sign_command",
    priority: 175,
    kicker: "JUJU HOTEL · EMERGENCY COMMAND",
    title: "열쇠보다 먼저 넘어간 권한",
    body: "펜촉이 종이의 마지막 줄을 지나자 Hayes는 승리한 사람처럼 웃지 않았다. 그는 문서를 접지도 않은 채 병사에게 입구 폭을 재게 했고, 프런트 뒤에서 지켜보던 주민들은 황동 열쇠가 아직 지배인의 손에 있다는 사실만 확인했다. 그러나 객실 명단을 누가 보고, 정문을 누가 열며, 보급품을 누가 배분할지는 이미 서명 한 줄로 바뀌었다. 호텔은 그날 밤부터 보호받는 피난처와 점령된 거점 사이의 좁은 문턱에 섰다.",
    quote: "열쇠는 가지고 계십시오. 이제 그 문을 언제 여는지는 제가 결정합니다.",
    image: "/juminjung/assets/cutscenes/hayes-command-signed-v1.png",
    imageAlt: "헤이즈 대령이 비 내리는 JUJU HOTEL 프런트에서 군 지휘권 문서의 서명을 지켜보고, 주민들이 계단에서 불안하게 바라보는 사이 병사가 입구 검문선을 재는 장면.",
  },
  {
    id: "hayes_civilian_command",
    triggerStoryEventId: "hayes-command",
    triggerStoryChoiceId: "civilian_rule",
    priority: 175,
    kicker: "JUJU HOTEL · CIVILIAN COMMAND",
    title: "총보다 먼저 놓인 호텔의 규칙",
    body: "Hayes는 서명되지 않은 지휘권 문서를 접지 않은 채 권총과 함께 프런트 위에 내려놓았다. 주민 대표들은 무기를 빼앗아 환호하는 대신 순찰표와 배급 장부, 객실 열쇠를 같은 불빛 아래 펼쳤다. Owen은 군복을 입은 사람도 문턱을 넘는 순간 호텔 규칙을 따라야 한다는 조항을 소리 내어 읽었다. Hayes의 병력은 남았고 방어선도 강해졌지만, 정문을 열고 보급품을 나누는 마지막 결정은 다시 호텔 사람들의 손으로 돌아왔다.",
    quote: "내 병력도 이 문턱을 넘는 순간, 당신들의 규칙을 따르겠습니다.",
    image: "/juminjung/assets/cutscenes/hayes-civilian-command-v1.png",
    imageAlt: "마커스 헤이스 대령이 비 내리는 JUJU HOTEL 프런트에서 권총과 미서명 지휘 문서를 황동 열쇠와 민간 장부 옆에 내려놓고, 오웬과 주민 협의체가 긴장된 표정으로 지켜보는 장면.",
  },
  {
    id: "owen_defense_force",
    triggerStoryEventId: "owen-future",
    triggerStoryChoiceId: "resistance",
    priority: 170,
    kicker: "JUJU HOTEL · CIVIL DEFENSE",
    title: "명령 없이 세운 방어선",
    body: "Owen은 군용 계급장을 떼어 프런트 장부 옆에 내려놓고, 투숙객들과 로비의 모든 출입로를 다시 걸었다. 누가 총을 들지보다 누가 아이들을 지하로 이끌고, 누가 부상자를 옮기고, 누가 마지막 바리케이드를 놓을지 먼저 정했다. 객실 문짝과 철제 선반은 번호가 붙은 방어 자재가 되었고, 보안 물자는 두 사람이 확인한 뒤에만 배분됐다. Hayes의 병력처럼 명령을 기다리는 부대가 아니라, 각자 다음 사람의 빈자리를 아는 방위대가 호텔 안에 생겼다.",
    quote: "이번 방어선은 누군가의 명령이 아니라, 여기 남기로 한 사람들의 약속입니다.",
    image: "/juminjung/assets/cutscenes/owen-defense-force-v1.png",
    imageAlt: "오웬 밀러가 JUJU HOTEL 로비에서 계급장을 내려놓고 주민들과 출입로 지도와 역할표를 점검하며 객실 문짝과 철제 선반으로 방어선을 준비하는 장면.",
  },
  {
    id: "owen_escape_route",
    triggerStoryEventId: "owen-future",
    triggerStoryChoiceId: "escape",
    priority: 169,
    kicker: "JUJU HOTEL · ESCAPE ROUTE",
    title: "방어선 밖의 길",
    body: "오웬 밀러는 군번줄을 셔츠 안으로 밀어 넣고, 망가진 소총과 작은 가방만 챙겨 호텔 후문에 섰다. 황동등 아래에는 그가 끝내 완성하지 않은 로비 방어 지도와 빈 의자가 남았다. 빗속의 탐조등이 골목 반대편을 훑는 사이 문이 열렸고, 그는 호텔의 불빛을 한 번 돌아본 뒤 차가운 통로로 몸을 옮겼다. 그가 나간 뒤 후문은 안에서 다시 봉쇄됐다. 그를 쫓는 군 차량의 소음도, 그 소리에 몰린 괴물도 호텔에서 멀어질 것이다. 그러나 공성이 닥치는 날, 그가 짜던 교대선과 후퇴 경로를 대신 완성할 사람은 없다.",
    quote: "제가 남으면 전쟁이 이 문을 찾아옵니다. 떠나면, 적어도 오늘 밤은 빗나가겠죠.",
    image: "/juminjung/assets/cutscenes/owen-escape-route-v1.png",
    imageAlt: "오웬 밀러가 낡은 가방과 손상된 소총을 들고 따뜻한 호텔 후문을 마지막으로 돌아본 뒤 빗속 탐조등이 훑는 차가운 골목으로 떠나며, 안쪽 탁자에는 미완성 방어 지도와 빈 의자가 남은 장면.",
  },
  {
    id: "vale_behavior_map",
    triggerStoryEventId: "vale-research",
    triggerStoryChoiceId: "complete",
    priority: 170,
    kicker: "BASEMENT LAB · BEHAVIOR MAP",
    title: "괴물에게도 반복되는 길이 있었다",
    body: "Vale가 살아 있는 샘플의 반응을 시간대별로 겹치자 불규칙해 보이던 파형이 도시 지도 위의 이동로와 맞물렸다. Lily는 지워진 최초 목격 기록을 복원해 같은 지점에 붉은 핀을 꽂았다. 괴물은 사람의 목소리를 흉내 냈지만, 기억을 고르는 순서와 비를 피하는 경로까지 바꾸지는 못했다. 두 사람은 결론을 금고에 감추지 않고 경비 교대 장부에 옮겼다. 이제 순찰대는 형체를 본 뒤 대응하는 대신, 그것이 나타날 복도를 먼저 비울 수 있었다.",
    quote: "정체를 다 알지는 못해도, 다음 움직임은 먼저 읽을 수 있어요.",
    image: "/juminjung/assets/cutscenes/vale-lily-research-v1.png",
    imageAlt: "에이드리언 베일 박사와 릴리 포스터가 JUJU HOTEL 지하 임시 연구실에서 밀봉된 검은 조직 샘플의 파형과 복원 문서, 도시 이동 지도를 대조해 괴물의 반복 경로를 찾아내는 장면.",
  },
  {
    id: "vale_research_destroyed",
    triggerStoryEventId: "vale-research",
    triggerStoryChoiceId: "destroy",
    priority: 170,
    kicker: "BASEMENT LAB · FINAL INCINERATION",
    title: "재가 된 행동 지도",
    body: "네가 소각 승인 스위치를 내리자 에이드리언 베일 박사는 밀봉된 검은 조직 샘플을 긴 집게로 들어 의료용 소각로 안에 넣었다. 유리관이 갈라지며 뻗어 나오던 가느다란 그림자는 불꽃 속에서 오그라들었고, 배관을 긁던 소리도 곧 멎었다. 주민들이 샘플에 노출될 위험은 사라졌고 호텔은 오늘 밤 더 조용해질 것이다. 그러나 도시 이동 지도와 파형 사진, 최초 관찰 장부가 차례로 불붙자 괴물이 반복해서 고르는 길도 증명할 수 없는 가설로 돌아갔다. 릴리 포스터와 함께 쓰던 빈 연구 의자 앞에서 마지막 붉은 핀이 재로 무너졌다. 이제 누구도 이 연구로 THE TRUTH에 도달하거나 다음 복도를 미리 비울 수 없었다.",
    quote: "모르는 것이 안전할 때도 있습니다. 오늘 이후에는, 무엇을 몰랐는지도 증명할 수 없겠지만요.",
    image: "/juminjung/assets/cutscenes/vale-research-destroyed-v1.png",
    imageAlt: "에이드리언 베일 박사가 JUJU HOTEL 지하 임시 연구실의 의료용 소각로에 밀봉된 검은 조직 샘플을 넣고, 릴리 포스터와 함께 만들던 행동 지도와 파형 기록이 빈 연구 의자 옆에서 불타는 장면.",
  },
  {
    id: "grace_mutual_aid",
    triggerStoryEventId: "grace-faith",
    triggerStoryChoiceId: "mutual_aid",
    priority: 165,
    kicker: "JUJU HOTEL · MUTUAL AID",
    title: "촛불을 내려놓은 손",
    body: "Grace는 집회에 쓰던 의자를 계단참에서 치우고, 닫힌 책과 꺼진 촛불 옆에 망치와 못, 석고 통을 놓았다. 사람들은 설교를 듣는 대신 깨진 난간을 붙잡고, 젖은 벽을 긁어 내고, 비가 새는 창을 천과 판자로 막았다. 누구도 믿음을 버리라고 요구하지 않았고, 누구도 믿음을 이유로 일을 지휘하지 않았다. 그날부터 구호조의 규칙은 단순했다. 함께 쓰는 곳은 함께 고치고, 가장 위험한 일은 혼자 하지 않는 것.",
    quote: "믿음은 제게 남겨 두고, 이 손은 모두가 딛는 계단을 고치게 할게요.",
    image: "/juminjung/assets/cutscenes/grace-mutual-aid-v1.png",
    imageAlt: "그레이스 할러웨이가 낡은 JUJU HOTEL 계단참에서 주민들과 난간과 벽, 빗물 새는 창을 함께 보수하는 장면.",
  },
  {
    id: "claire_nursery",
    triggerStoryEventId: "claire-future",
    triggerStoryChoiceId: "nursery",
    priority: 165,
    kicker: "JUJU HOTEL · SAFE NURSERY",
    title: "밤을 낮게 밝히는 방",
    body: "Claire는 깨진 객실 하나에서 무거운 가구를 문 쪽으로 옮기고, 남은 천으로 침상 사이에 작은 칸막이를 쳤다. 밝은 전등 대신 덮개를 씌운 황동등 하나만 남겼고, 병뚜껑과 오래된 열쇠로 만든 모빌은 바람이 불 때에도 작은 소리만 냈다. 아이와 임신한 주민이 먼저 잠들자 복도의 발걸음도 자연스럽게 느려졌다. 이곳은 세상이 안전하다고 거짓말하는 방이 아니라, 적어도 오늘 밤의 공포를 함께 낮춰 주는 방이 되었다.",
    quote: "조용한 밤 하나가 사치라면, 그 사치는 우리가 지켜야 해요.",
    image: "/juminjung/assets/cutscenes/claire-safe-nursery-v1.png",
    imageAlt: "임신한 클레어 노박이 낡은 JUJU HOTEL 객실의 안전 육아실에서 잠든 아이에게 담요를 덮어 주고, 천 칸막이 뒤 다른 임신한 주민이 쉬는 장면.",
  },
  {
    id: "eli_safe_passage",
    triggerStoryEventId: "eli-keyring",
    triggerStoryChoiceId: "pathfinder",
    priority: 165,
    kicker: "JUJU HOTEL · SAFE PASSAGE",
    title: "훔친 열쇠 대신 그린 길",
    body: "Eli는 정문으로 이어지는 큰길을 지도에서 지우고, 무너진 세탁소 뒤편과 배수로, 두 건물 사이의 좁은 서비스 통로를 하나의 길로 이었다. 눈에 띄는 표지판 대신 비에 쉽게 씻기는 분필과 천 조각만 남겼다. 그날 새벽, 보급 주머니를 든 두 사람이 괴물의 흔적이 남은 대로를 피해 호텔 뒤편에 도착했다. 누구도 Eli를 감시하러 따라가지 않았다. 그는 처음으로 훔친 물건이 아니라, 모두가 돌아올 수 있는 길을 들고 돌아왔다.",
    quote: "표시는 오래 남으면 안 돼. 사람은 찾고, 저것들은 지나치게 해야 하니까.",
    image: "/juminjung/assets/cutscenes/eli-safe-passage-v1.png",
    imageAlt: "엘리가 비 내린 폐허의 골목 벽에 작은 분필 표시를 남기고, 보급 주머니를 든 주민들이 위험한 큰길을 피해 JUJU HOTEL로 향하는 장면.",
  },
  {
    id: "rosa_household_network",
    triggerStoryEventId: "rosa-family",
    triggerStoryChoiceId: "household",
    priority: 165,
    kicker: "JUJU HOTEL · SHARED HOUSEHOLDS",
    title: "객실 번호 사이에 생긴 가족",
    body: "Rosa는 사람들을 혈연이 아니라 하루의 일을 나눌 수 있는 작은 생활조로 묶었다. 한 조는 공동 세면대의 물을 받아 객실 주전자에 나눴고, 다른 조는 젖은 옷과 붕대를 한 번에 씻어 난방관 곁에 걸었다. 아이와 노인이 있는 방에는 먼저 따뜻한 물이 돌아갔다. 각자 잠근 객실 문은 그대로였지만, 복도에는 누가 오늘 물을 길었고 누가 내일 늦잠을 자도 되는지 아는 사람들이 생겼다.",
    quote: "가족은 같은 피가 아니라, 누가 물을 길 차례인지 기억해 주는 사람들이에요.",
    image: "/juminjung/assets/cutscenes/rosa-household-network-v1.png",
    imageAlt: "로사 마르티네즈가 JUJU HOTEL 복도 공동 세면대에서 주민들과 물을 주전자에 나누고, 다른 주민들이 젖은 옷과 붕대를 함께 씻어 난방관 곁에 거는 장면.",
  },
  {
    id: "ruth_care_team",
    triggerStoryEventId: "ruth-home",
    triggerStoryChoiceId: "care_team",
    priority: 165,
    kicker: "JUJU HOTEL · COMMUNITY CARE",
    title: "병실 밖으로 이어진 돌봄",
    body: "Ruth는 진료실 문에 걸려 있던 교대표를 복도 벽으로 옮겼다. 아이가 잠들지 못한 시간, 붕대를 바꿔야 할 객실, 혼자 계단을 오르기 힘든 사람의 이름 옆에 투숙객들이 차례로 자신의 시간을 적었다. 약품이 없는 자리에는 따뜻한 물과 깨끗한 천, 함께 앉아 줄 의자가 놓였다. 돌봄은 더는 의료진 두 사람의 밤샘이 아니라 호텔 전체가 지키는 생활 규칙이 되었다.",
    quote: "살리는 일은 치료가 끝난 뒤에도 계속돼요. 이제 그 시간을 나눠 가질 수 있어요.",
    image: "/juminjung/assets/cutscenes/ruth-community-care-v1.png",
    imageAlt: "루스 벨이 낡은 JUJU HOTEL 복도에서 공동 돌봄 교대표를 정리하고, 주민들이 아이와 부상자의 객실에 따뜻한 물과 붕대, 의자를 가져가는 장면.",
  },
  {
    id: "samuel_civil_guard",
    triggerStoryEventId: "samuel-duty",
    triggerStoryChoiceId: "watch",
    priority: 165,
    kicker: "JUJU HOTEL · CIVILIAN NIGHT WATCH",
    title: "명령 대신 건네받은 열쇠",
    body: "Samuel은 낡은 경찰 배지를 프런트 서랍 안에 내려놓고, 그 자리에 호텔의 황동 열쇠고리를 받았다. 새 경비대는 계급도 제복도 없이 객실 사람들의 이름과 순찰 시간을 함께 적었다. 손전등과 호루라기, 동쪽 철문부터 계단참까지 이어진 지도가 카운터 위에 놓였다. 그가 다시 선 검문선은 사람을 버리기 위한 경계가 아니라, 누가 돌아오지 않았는지 책임지는 약속이 되었다.",
    quote: "이번에는 문을 닫으라는 명령이 아니라, 안의 사람들을 지키겠다는 약속입니다.",
    image: "/juminjung/assets/cutscenes/samuel-civil-guard-v1.png",
    imageAlt: "새뮤얼 프라이스가 JUJU HOTEL 프런트 서랍에 낡은 경찰 배지를 내려놓고 주민에게서 황동 객실 열쇠고리를 받는 동안, 뒤에서 민간 경비대원들이 손전등과 순찰 지도를 준비하는 장면.",
  },
  {
    id: "noah_community_table",
    triggerStoryEventId: "noah-table",
    triggerStoryChoiceId: "community_kitchen",
    priority: 165,
    kicker: "JUJU HOTEL · COMMON TABLE",
    title: "배급표 대신 놓인 접시",
    body: "Noah는 잠겨 있던 식당 문을 열고 남은 통조림과 말린 뿌리, 향신료를 한 냄비에 모았다. 장부의 몫은 그대로였지만 따로 끓일 때 버리던 물과 불, 남은 조각이 한 끼로 돌아왔다. 투숙객들은 객실 번호가 아니라 빈 의자 순서대로 앉았다. 부엌 열쇠는 다시 그의 허리에 있었고, 배급 기록은 누구나 볼 수 있는 식탁 끝에 놓였다.",
    quote: "더 만든 게 아니에요. 버리지 않고 같이 먹은 겁니다.",
    image: "/juminjung/assets/cutscenes/noah-community-table-v1.png",
    imageAlt: "노아 그랜트가 낡은 JUJU HOTEL 식당의 긴 공동 식탁에 따뜻한 스튜를 나누고, 투숙객들이 객실 번호 대신 빈 의자에 둘러앉은 가운데 공개 배급 장부가 놓인 장면.",
  },
  {
    id: "thomas_microgrid_online",
    triggerStoryEventId: "thomas-grid",
    triggerStoryChoiceId: "microgrid",
    priority: 165,
    kicker: "JUJU HOTEL · INDEPENDENT POWER",
    title: "꺼지지 않는 세 개의 불빛",
    body: "Thomas가 마지막 차단기를 올리자 발전기실의 진동이 낮고 고른 박자로 바뀌었다. 벽을 따라 새로 묶은 배선은 진료 구역, 프런트 라디오, 동쪽 방벽의 표시등으로 갈라졌다. 객실 조명은 여전히 필요한 만큼만 켜졌지만, 어느 한쪽을 살리기 위해 다른 쪽을 완전히 포기할 필요는 없어졌다. 낡은 계기판의 바늘이 안정 구간에 머문 채 첫 밤의 부하를 견뎠다.",
    quote: "전기가 남은 게 아니에요. 낭비하던 전기를 되찾은 겁니다.",
    image: "/juminjung/assets/cutscenes/thomas-microgrid-online-v1.png",
    imageAlt: "토머스 리가 JUJU HOTEL 발전기실의 새 배전반을 올리고, 정돈된 배선이 진료 구역과 프런트 라디오, 동쪽 방벽 표시등으로 이어지는 가운데 계기판이 안정 구간을 가리키는 장면.",
  },
  {
    id: "hazel_perimeter_watch",
    triggerStoryEventId: "hazel-watch",
    triggerStoryChoiceId: "ranger",
    priority: 165,
    kicker: "JUJU HOTEL · OUTER PERIMETER",
    title: "괴물보다 먼저 울리는 종",
    body: "Hazel은 Vale가 표시한 이동로를 따라 철사와 빈 통, 프런트에서 떼어 낸 작은 황동 종을 호텔 외곽에 연결했다. 마지막 매듭을 당기자 동쪽 담장 끝에서 낮은 종소리가 차례로 돌아왔다. 그것은 괴물을 쓰러뜨리는 덫이 아니었다. 어둠이 철문에 닿기 전에 복도의 불을 깨우고, 잠든 사람들이 각자의 자리를 찾게 하는 경보였다.",
    quote: "이제 저것들이 먼저 우리를 보는 밤은 끝이야.",
    image: "/juminjung/assets/cutscenes/hazel-perimeter-watch-v1.png",
    imageAlt: "헤이즐 퀸이 비 내리는 JUJU HOTEL 외곽 담장에서 철사와 황동 종으로 만든 조기경보 장치를 점검하고, 멀리 따뜻한 호텔 창문과 안개 속 형체들이 보이는 장면.",
  },
  {
    id: "eleanor_clinic_opened",
    triggerStoryEventId: "eleanor-standard",
    triggerStoryChoiceId: "clinic",
    priority: 165,
    kicker: "JUJU HOTEL · MEDICAL CARE ZONE",
    title: "객실 하나가 진료소가 된 아침",
    body: "객실 문에서 황동 번호표를 떼어낸 자리에 흰 천 조각이 걸렸다. Eleanor는 남은 약품을 증상별로 나누고, 침대 두 개 사이에 진료 장부와 소독 도구를 놓았다. 복도에서 기다리던 사람들은 더는 아픈 몸을 숨긴 채 방을 구하지 않아도 되었다. JUJU HOTEL의 객실 하나가 잠자리 대신 매일 밤 사람을 살피는 상설 진료 구역이 되었다.",
    quote: "치료할 방이 생겼으니, 이제 늦기 전에 찾아낼 수 있어요.",
    image: "/juminjung/assets/cutscenes/eleanor-hotel-clinic-v1.png",
    imageAlt: "엘리너 리드가 낡은 JUJU HOTEL 객실을 개조한 작은 상설 진료소에서 약품과 진료 장부를 정리하고, 따뜻한 황동 램프 아래 붕대를 감은 환자를 살피는 장면.",
  },
  {
    id: "eleanor_mobile_rounds",
    triggerStoryEventId: "eleanor-standard",
    triggerStoryChoiceId: "mobile",
    priority: 165,
    kicker: "JUJU HOTEL · MOBILE ROUNDS",
    title: "진료소가 없는 복도",
    body: "엘리너 리드는 남은 약을 한 객실에 쌓아 두는 대신 낡은 왕진 가방에 나누어 담았다. 황동 램프 하나와 금속 쟁반을 복도 바닥에 내려놓고 가장 위급한 주민의 붕대를 다시 감는 동안, 닫힌 문 너머에서는 다음 차례를 기다리는 기침과 발소리가 이어졌다. 오늘 밤에도 한 사람은 확실히 나아질 것이다. 그러나 고정된 진료실도, 호텔 전체의 발병을 미리 막을 장비도 없었다. 그녀가 호텔을 떠나는 날에는 이 복도 진료도 함께 끝날 것이다.",
    quote: "모두를 한 방에 부를 수 없다면, 너무 늦기 전에 제가 찾아가야죠.",
    image: "/juminjung/assets/cutscenes/eleanor-mobile-rounds-v1.png",
    imageAlt: "엘리너 리드가 낡은 왕진 가방과 황동 램프를 호텔 복도에 내려놓고 부상자의 붕대를 갈며, 뒤로 닫힌 여러 객실 문이 이어지는 장면.",
  },
  {
    id: "walter_archive_opened",
    triggerStoryEventId: "walter-key",
    triggerStoryChoiceId: "use_key",
    priority: 165,
    kicker: "BASEMENT ARCHIVE · FIRST ENTRY",
    title: "아버지가 잠가 둔 기록실",
    body: "황동 열쇠가 돌아가자 녹슨 잠금장치 안쪽에서 오래 붙어 있던 금속이 찢어지는 소리가 났다. Walter는 손전등으로 먼지 쌓인 장부와 릴 테이프, 도시 지도, 인간의 몸을 닮은 도해를 차례로 비췄다. 첫 장부에는 재난 전 인간의 기억 반응을 모사한 조직 샘플과 호텔 발전기 부품, 진정제가 같은 발생 구역으로 옮겨졌다고 적혀 있었다. 마지막 페이지에는 네 아버지가 이 방의 봉인을 지시한 서명이 남아 있었다. Walter는 문턱을 넘지 않은 채 네 아버지 곁에서 이 방을 잠갔던 밤을 기억했다. 전원이 끊긴 라디오의 눈금은 91.3에 멈춰 있었고, 문이 열린 뒤 배관 깊은 곳에서 같은 금속성 마찰음이 한 번 되돌아왔다.",
    quote: "네 아버지가 감춘 건 비밀이 아니었다. 우리가 열 준비가 되지 않은 문이었다.",
    image: "/juminjung/assets/cutscenes/walter-basement-archive-v1.png",
    imageAlt: "월터 브릭스가 황동 열쇠와 손전등을 든 채 처음 열린 JUJU HOTEL 지하 기록실 문에 서 있고, 안쪽에 먼지 쌓인 장부와 릴 테이프, 라디오, 도시 지도와 생체 도해가 드러난 장면.",
  },
  {
    id: "walter_key_hidden",
    triggerStoryEventId: "walter-key",
    triggerStoryChoiceId: "hide_key",
    priority: 165,
    kicker: "BASEMENT ARCHIVE · SEALED",
    title: "열쇠가 사라진 벽",
    body: "네가 황동 열쇠를 돌려주자 Walter는 그것을 지하 복도 배전함 안쪽에 걸고 두꺼운 철판을 덮었다. 마지막 나사를 조이자 사슬로 묶인 기록실 문과 호텔 사이에 다시 침묵이 내려앉았다. 문 너머의 장부와 릴 테이프, 아버지가 남긴 기록은 손대지 않은 채 잠겼고 배관 깊은 곳의 금속성 마찰음도 멎었다. 오늘 밤 호텔은 더 안전할 것이다. 하지만 잠들어 있던 91.3MHz 라디오와 괴물의 첫 기록, 아버지가 돌아올 길을 가리킬 좌표도 그 벽 뒤에서 함께 사라졌다.",
    quote: "문을 열지 않는 것도 선택이다. 다만 닫아 둔 진실은 우리를 찾아오지 않아.",
    image: "/juminjung/assets/cutscenes/walter-key-hidden-v1.png",
    imageAlt: "월터 브릭스가 낡은 JUJU HOTEL 지하 복도에서 황동 열쇠를 벽 속 정비함에 넣고 철판을 조이는 동안, 뒤편의 기록실 철문은 사슬과 빗장으로 봉인된 채 차가운 빛을 가두고 있는 장면.",
  },
  {
    id: "mia_daniel_reunion",
    triggerStoryEventId: "mia-family",
    triggerStoryChoiceId: "reunite",
    priority: 160,
    kicker: "ROOM KEY 103 · FAMILY FOUND",
    title: "사진 속 두 사람이 다시 만난 밤",
    body: "다니엘은 미아가 품고 있던 토끼 인형의 찢어진 귀를 알아보았다. 미아는 곧장 달려가지 않았다. 비에 젖은 남자가 사진 속 아버지와 같은 목소리로 오래전 약속을 말할 때까지, 프런트의 황동 램프 아래에서 한 걸음씩 다가갔다. 다니엘이 무릎을 꿇자 아이의 손이 먼저 그의 얼굴에 닿았다.",
    quote: "방을 찾으러 온 두 사람은, 서로가 돌아갈 곳이라는 걸 가장 늦게 알았다.",
    image: "/juminjung/assets/cutscenes/mia-daniel-reunion-v1.png",
    imageAlt: "폭우가 내리는 낡은 JUJU HOTEL 복도에서 토끼 인형을 안은 미아가 한 손을 내밀고, 지친 다니엘이 무릎을 꿇어 조심스럽게 딸과 재회하는 장면.",
  },
  {
    id: "daniel_mia_choice",
    triggerStoryEventId: "daniel-family",
    triggerStoryChoiceId: "let_choose",
    priority: 160,
    kicker: "FRONT DESK · HER ANSWER FIRST",
    title: "아이가 대답할 때까지",
    body: "프런트 위에는 황동 객실 열쇠와 접힌 도로지도가 나란히 놓였다. Daniel은 Mia의 눈높이까지 몸을 낮추고 어느 쪽도 가리키지 않은 채 손을 펼쳤다. Mia는 해진 토끼 인형을 안고 오래 두 선택을 바라보았다. 누구도 아버지라는 말이나 안전이라는 말로 대답을 재촉하지 않았다. 그날 JUJU HOTEL은 아이에게 방만 내어 준 것이 아니라, 어디를 집이라고 부를지 정할 시간까지 내어 주었다.",
    quote: "가족이라는 말은 아이의 대답보다 먼저 문을 열 수 없었다.",
    image: "/juminjung/assets/cutscenes/daniel-mia-choice-v1.png",
    imageAlt: "비 내리는 밤의 JUJU HOTEL 프런트에서 Daniel Carter가 Mia Carter의 눈높이에 앉아 손을 펼치고, 토끼 인형을 안은 Mia가 황동 객실 열쇠와 접힌 도로지도 사이에서 자신의 선택을 생각하는 장면.",
  },
  {
    id: "carter_safe_passage",
    triggerStoryEventId: "daniel-family",
    triggerStoryChoiceId: "escort",
    priority: 160,
    kicker: "EAST GATE · SAFE PASSAGE",
    title: "둘이서 호텔 문을 나선 새벽",
    body: "배급 장부에서 식량 두 몫을 덜어 낸 뒤, 관리자는 지도에 순찰대가 확인한 길을 표시했다. Daniel은 보급품을 묶은 배낭을 메고 한 손으로 Mia의 손을 잡았다. Mia는 다른 팔에 토끼 인형을 끼운 채 빗물이 고인 동쪽 철문을 건넜다. 두 사람은 몇 걸음 뒤에 한 번만 돌아보았다. 황동 램프가 켜진 호텔 문은 닫히지 않은 채, 돌아올 사람의 방향을 오래 비추고 있었다.",
    quote: "떠나는 사람에게도 방은 필요하다. 돌아올 수 있다는 기억의 방.",
    image: "/juminjung/assets/cutscenes/carter-safe-passage-v1.png",
    imageAlt: "차가운 새벽의 JUJU HOTEL 동쪽 철문에서 보급품과 배낭을 든 Daniel Carter가 토끼 인형을 안은 Mia Carter의 손을 잡고 안전지대 길로 떠나며 따뜻한 호텔 입구를 돌아보는 장면.",
  },
  {
    id: "white_door_accepted",
    triggerStoryEventId: "white-answer",
    triggerStoryChoiceId: "yes",
    priority: 170,
    kicker: "BASEMENT THRESHOLD · ADMIT THE UNKNOWN",
    title: "사람의 기억을 가진 것을 들이다",
    body: "황동 마스터키가 돌아가자 지하 기록실 너머의 벽이 문처럼 갈라졌다. 차가운 빛 속에는 사라진 사람들의 사진과 목소리, 아직 주인을 찾지 못한 기억들이 겹쳐 떠올랐다. Mr. White는 안으로 들어가지 않았다. 대신 문턱 곁에 서서 호텔이 그 존재들을 손님으로 부를 수 있을 때까지 자신이 첫 번째 증인이 되겠다고 말했다. 로비의 규칙은 그날 밤 처음으로 인간인지 아닌지가 아니라, 문 안에서 누구도 해치지 않을 수 있는지를 묻게 되었다.",
    quote: "문을 연 것은 열쇠가 아니라, 모르는 것을 곧바로 적으로 부르지 않겠다는 대답이었다.",
    image: "/juminjung/assets/cutscenes/white-door-accepted-v1.png",
    imageAlt: "황동 램프가 켜진 JUJU HOTEL 지하 기록실에서 낡은 흰 코트를 입은 Mr. White가 열린 문턱 곁에 서 있고, 관리자가 황동 열쇠를 든 채 차가운 빛과 겹쳐진 인간의 기억 형체들을 마주하는 장면.",
  },
  {
    id: "white_banished",
    triggerStoryEventId: "white-answer",
    triggerStoryChoiceId: "no",
    priority: 170,
    kicker: "SERVICE EXIT · CLOSE THE DOOR",
    title: "문을 잠그고 한 사람을 내보내다",
    body: "지하 방화문에 두 번째 사슬이 걸리고, Mr. White의 객실 열쇠는 프런트 고리에서 빠졌다. 그는 변명도 위협도 하지 않은 채 차가운 빗속으로 한 걸음 물러났다. 투숙객들은 따뜻한 로비 안에서 숨을 돌렸지만, 라디오는 전원을 뽑은 뒤에도 91.3의 잡음을 짧게 흘렸다. 호텔은 오늘 밤 안전해졌다. 다만 문밖으로 내보낸 것이 괴물이었는지, 진실을 아는 마지막 사람이었는지는 누구도 장부에 적지 못했다.",
    quote: "문은 닫혔다. 그러나 우리가 내보낸 것의 이름까지 잠긴 것은 아니었다.",
    image: "/juminjung/assets/cutscenes/white-banished-v1.png",
    imageAlt: "비 내리는 JUJU HOTEL 출구 밖에서 젖은 흰 코트의 Mr. White가 조용히 뒤돌아보고, 안쪽의 관리자가 황동 열쇠를 든 채 사슬로 봉쇄한 지하 방화문과 불안한 생존자들을 지키는 장면.",
  },
  {
    id: "hotel_siege_held",
    triggerEventId: "hotel_siege",
    triggerChoiceId: "hold_lobby",
    priority: 150,
    kicker: "JUJU HOTEL · LOBBY DEFENSE",
    title: "호텔이 마지막 문이 된 밤",
    body: "유리벽이 안쪽으로 휘어질 때마다 황동 열쇠들이 한꺼번에 울렸다. 투숙객들은 프런트와 소파를 밀어 방어선을 세웠고, 남은 보안 물자와 부품을 바리케이드에 쏟았다. 선두에 선 한 사람이 쓰러진 뒤에야 폭우 속 형체들이 물러났다. 로비는 부서졌지만, 아침까지 호텔의 문은 안쪽에서 잠겨 있었다.",
    quote: "우리는 승리한 것이 아니라, 오늘 밤의 마지막 문을 지켰다.",
    image: "/juminjung/assets/cutscenes/hotel-siege-v1.png",
    imageAlt: "폭우와 번개 속 비인간적인 형체들이 JUJU HOTEL 로비 유리벽을 밀어붙이고, 생존자들이 바리케이드를 붙들며 부상자를 후송하고 손전등으로 방어하는 대규모 공성 장면.",
  },
  {
    id: "hotel_siege_retreat",
    triggerEventId: "hotel_siege",
    triggerChoiceId: "retreat_basement",
    priority: 150,
    kicker: "JUJU HOTEL · LOWER SHELTER",
    title: "로비를 내어주고 사람을 지켰다",
    body: "관리자는 객실 열쇠 대신 지하 방화문 열쇠를 들었다. 마지막 사람이 계단 아래로 사라지자 로비 유리벽이 무너졌고, 형체들은 프런트와 발전기 배선을 짓밟았다. 누구도 뒤에 남지 않았지만, 위층에서 들려오는 발소리는 호텔이 더는 완전한 피난처가 아니라는 사실을 밤새 되풀이했다.",
    quote: "건물은 다시 세울 수 있다. 하지만 오늘 포기한 층을 되찾으려면 또 다른 밤을 견뎌야 한다.",
    image: "/juminjung/assets/cutscenes/hotel-siege-v1.png",
    imageAlt: "폭우 속 비인간적인 형체들이 JUJU HOTEL 로비 유리벽을 돌파하려는 동안 생존자들이 지친 투숙객을 부축해 지하로 후퇴하고, 관리자가 마지막으로 방어선을 확인하는 장면.",
  },
  {
    id: "first_night",
    priority: 10,
    minimumCompletedDay: 1,
    maximumCompletedDay: 1,
    kicker: "FIRST NIGHT · 03:07 AM",
    title: "호텔이 숨을 죽인 시간",
    body: "마지막 순찰을 마치고 장부를 펼쳤지만, 적을 이름도 없이 식량과 연료만 셌다. 라디오는 같은 주파수를 맴돌았고 복도 끝의 문은 아까보다 조금 더 열려 있었다. 아버지가 없는 첫날 밤, 호텔의 모든 소리가 누군가의 발걸음처럼 들렸다.",
    quote: "아침까지 문을 지키는 것. 오늘 해야 할 일은 그것뿐이다.",
    image: "/juminjung/assets/cutscenes/first-night-v1.png",
    imageAlt: "낡은 JUJU HOTEL 프런트 장부와 라디오 너머로 비어 있는 어두운 복도가 길게 이어지는 첫날 밤.",
  },
  {
    id: "generator_blackout",
    triggerEventId: "generator_failure",
    triggerChoiceId: "blackout",
    priority: 140,
    kicker: "BLACKOUT · 02:41 AM",
    title: "호텔이 반쪽으로 어두워진 순간",
    body: "발전기가 마지막 기침을 토해내자 당신은 로비와 객실 한 동의 차단기를 내렸다. 황동 램프와 라디오가 동시에 죽었고, 붉은 비상등 몇 개만 복도 끝을 간신히 붙잡았다. 프런트의 손전등으로도 객실 열쇠 번호는 읽히지 않았다. 번개가 창을 가른 짧은 순간, 빗속의 그림자들이 창 바로 밖에 몰려든 모습이 드러났다.",
    quote: "어둠은 빈 공간이 아니었다. 우리가 보지 못하는 동안에도 무언가는 움직였다.",
    image: "/juminjung/assets/cutscenes/generator-blackout-v1.png",
    imageAlt: "발전기 출력이 부족해 전력을 차단한 낡은 호텔 로비에서 생존자들이 손전등과 붉은 비상등에 의지하고, 폭우가 치는 창 바로 밖에 여러 인영이 몰려든 장면.",
  },
  {
    id: "guest_attacked",
    triggerEventId: "perimeter_breach",
    triggerChoiceId: "fight",
    priority: 150,
    kicker: "BREACH · FRONT LOBBY",
    title: "쓰러진 사람, 남겨진 열쇠",
    body: "철문이 안쪽으로 꺾이자 투숙객 한 명이 무너진 현관 쪽으로 뛰어들었다. 한 번의 충돌 뒤 그는 피와 빗물을 끌며 프런트 뒤로 돌아왔고, 다른 생존자가 그의 어깨를 붙잡아 카운터 아래로 끌어내렸다. 깨진 유리 너머의 형체는 쓰러진 사람을 쫓지 않았다. 기울어진 고개는 카운터의 황동 열쇠들을 향하고 있었다.",
    quote: "문을 막은 건 사람이었지만, 저것이 찾은 건 사람이 아니었다.",
    image: "/juminjung/assets/cutscenes/hotel-breach-guest-attack-v1.png",
    imageAlt: "파손된 호텔 로비에서 한 생존자가 프런트 카운터 뒤의 부상자를 끌어내고, 폭우 속 괴물 형체가 무너진 바리케이드 너머에 서 있는 장면.",
  },
  {
    id: "first_monster_sighting",
    triggerEventId: "perimeter_breach",
    priority: 100,
    kicker: "FIRST SIGHTING · EAST GATE",
    title: "철문 너머에 서 있던 것",
    body: "번개가 로비를 하얗게 가른 순간, 빗속의 형체가 사람보다 한 뼘 더 길게 몸을 폈다. 그것은 문을 두드리지 않았다. 손가락 하나로 휘어진 철문을 천천히 짚었고, 라디오에서는 아버지의 주파수와 같은 잡음이 흘렀다.",
    quote: "사람처럼 보인다고 해서 전부 들이지는 마.",
    image: "/juminjung/assets/cutscenes/first-monster-sighting-v1.png",
    imageAlt: "차가운 빗속에서 비정상적으로 긴 괴물이 JUJU HOTEL의 휘어진 철문 너머에 서 있는 첫 목격 장면.",
  },
  {
    id: "room_body_discovery",
    triggerEventId: "room_body_discovery",
    priority: 130,
    kicker: "ROOM 207 · 05:18 AM",
    title: "안에서 잠긴 객실",
    body: "마스터키로 207호를 열자 빗물 냄새보다 먼저 오래된 피와 젖은 석회의 냄새가 밀려왔다. 시신은 침대 시트 아래에 있었고 황동 열쇠는 문 안쪽 바닥에 놓여 있었다. 검은 흔적은 시신 앞에서 시작해 깨진 창문에서 끝났다. 누군가 들어온 흔적은 없었지만, 무언가는 이 방에서 나간 뒤였다.",
    quote: "문은 밤새 잠겨 있었다. 그렇다면 우리가 잠근 것은 무엇이었을까.",
    image: "/juminjung/assets/cutscenes/room-207-body-discovery-v1.png",
    imageAlt: "비 내리는 새벽의 낡은 JUJU HOTEL 207호에서 두 생존자가 시트로 완전히 덮인 시신과 창가에서 이어진 검은 흔적, 바닥의 황동 열쇠를 발견한 장면.",
  },
  {
    id: "father_radio_signal",
    triggerEventId: "father_radio_signal",
    priority: 120,
    kicker: "91.3 MHz · 01:13 AM",
    title: "죽어 있던 주파수의 목소리",
    body: "잡음 사이로 아버지만 쓰던 호출명이 세 번 반복됐다. 목소리는 대답하지 말라는 경고와 함께 서로 다른 세 중계기의 좌표를 차례로 읽었다. 지도에서 초록색 호텔 표식과 세 붉은 송신점을 연결하자, 붉은 삼각형은 호텔이 아니라 재난 최초 발생 구역을 에워쌌다. 세 송신기가 같은 기억을 되풀이하는 덫인지, 아버지가 자신의 위치를 숨긴 구조 신호인지는 아직 알 수 없었다.",
    quote: "그 목소리는 집으로 돌아오겠다고 하지 않았다. 먼저 자신을 찾아내라고 했다.",
    image: "/juminjung/assets/cutscenes/father-radio-signal-v1.png",
    imageAlt: "폭우가 내리는 JUJU HOTEL 프런트에서 두 생존자가 갑자기 켜진 낡은 라디오와 세 송신 지점을 표시한 도시 지도를 바라보고, 깨진 창밖의 긴 그림자를 경계하는 장면.",
  },
  {
    id: "father_at_gate_quarantine",
    triggerEventId: "father_at_gate",
    triggerChoiceId: "quarantine_verify",
    priority: 125,
    kicker: "EAST GATE · QUARANTINE",
    title: "기억은 같고, 피는 달랐다",
    body: "그는 아버지와 나만 알던 세 가지 질문에 모두 답했다. 그러나 철문 아래로 밀어 넣은 혈액 표본은 인간의 체온에서 굳지 않았고, Vale의 시약은 검은 고리처럼 번졌다. 경비는 철문을 잠근 채 바깥 격리선을 세웠다. 아버지의 기억이 돌아온 것인지, 기억만 돌아온 것인지는 아직 말할 수 없었다.",
    quote: "목소리는 아버지였다. 표본은 아니었다.",
    image: "/juminjung/assets/cutscenes/father-at-gate-v1.png",
    imageAlt: "폭우 속 JUJU HOTEL의 잠긴 철문 밖에 낡은 가방을 든 중년 남성이 서 있고, 안쪽의 젊은 관리자가 황동 마스터키를 쥔 채 검증용 트레이와 등불 너머로 그를 경계하는 장면.",
  },
  {
    id: "father_at_gate_opened",
    triggerEventId: "father_at_gate",
    triggerChoiceId: "open_gate",
    priority: 125,
    kicker: "EAST GATE · ADMIT ONE",
    title: "황동 열쇠가 돌아가기 직전",
    body: "그는 가방을 열어 아버지만 알던 발전기 부품과 봉인 연료를 바닥에 내려놓았다. 세 가지 기억도 틀리지 않았다. 경비가 물러나고 황동 열쇠가 자물쇠에 닿자, 복도의 투숙객들은 숨을 죽였다. 사람을 들이는 규칙을 지켜 온 호텔은 이번 한 번만 신원보다 기억을 먼저 믿기로 했다.",
    quote: "문이 열린 뒤에야, 나는 우리가 누구를 맞이했는지 다시 묻게 되었다.",
    image: "/juminjung/assets/cutscenes/father-at-gate-v1.png",
    imageAlt: "폭우 속 JUJU HOTEL의 잠긴 철문 밖에 발전기 물자가 든 가방을 내려놓은 중년 남성이 서 있고, 안쪽의 젊은 관리자가 문을 열기 직전 황동 마스터키를 쥔 장면.",
  },
  {
    id: "refugees_sheltered",
    triggerEventId: "refugee_wave",
    triggerChoiceId: "shelter",
    priority: 80,
    minimumCompletedDay: 8,
    kicker: "THE TURNING KEY · EAST GATE",
    title: "철문을 여는 손",
    body: "젖은 얼굴들이 철창 너머에서 대답을 기다렸다. 아이의 기침이 다시 들리자 당신은 바리케이드의 빗장을 풀고 황동 열쇠를 돌렸다. 문이 열리는 몇 분 동안 바깥의 그림자도 호텔을 보았지만, 오늘 밤 JUJU HOTEL은 다시 사람이 사는 곳이 될 것이다.",
    quote: "방은 없어도, 지붕은 나눌 수 있다.",
    image: "/juminjung/assets/cutscenes/refugees-at-gate-v1.png",
    imageAlt: "차가운 폭우 속에서 아이를 안은 보호자와 노인 등 피난민들이 JUJU HOTEL 철문 앞에 모여 도움을 청하는 장면.",
  },
  {
    id: "refugees_denied",
    triggerEventId: "refugee_wave",
    triggerChoiceId: "deny",
    priority: 80,
    minimumCompletedDay: 8,
    kicker: "THE CLOSED GATE · EAST GATE",
    title: "철문 밖에 남은 발자국",
    body: "램프를 끄자 바깥의 얼굴들이 하나씩 어둠에 잠겼다. 아이의 기침 소리는 빗소리에 묻힐 때까지 오래 남았다. 새벽이 왔을 때 철문 앞에는 작은 신발 자국과, 호텔 쪽을 향해 눌린 손바닥 자국만 남아 있었다.",
    quote: "문을 지켰다. 그러나 무엇을 지킨 것인지는 장부에 적히지 않았다.",
    image: "/juminjung/assets/cutscenes/refugees-at-gate-v1.png",
    imageAlt: "차가운 폭우 속에서 아이를 안은 보호자와 노인 등 피난민들이 JUJU HOTEL 철문 앞에 모여 도움을 청하는 장면.",
  },
];

export function getCutscene(id: string | null): CutsceneDefinition | null {
  return CUTSCENES.find((cutscene) => cutscene.id === id) ?? null;
}
