import type { CutsceneDefinition } from "./types.ts";

export const CUTSCENES: CutsceneDefinition[] = [
  {
    id: "noah_community_table",
    triggerStoryEventId: "noah-table",
    triggerStoryChoiceId: "community_kitchen",
    priority: 165,
    kicker: "JUJU HOTEL · COMMON TABLE",
    title: "배급표 대신 놓인 접시",
    body: "Noah는 잠겨 있던 식당 문을 열고 남은 통조림과 말린 뿌리, 향신료를 한 냄비에 모았다. 장부의 몫은 그대로였지만 따로 끓일 때 버리던 물과 불, 남은 조각이 한 끼로 돌아왔다. 투숙객들은 객실 번호가 아니라 빈 의자 순서대로 앉았다. 부엌 열쇠는 다시 그의 허리에 있었고, 배급 기록은 누구나 볼 수 있는 식탁 끝에 놓였다.",
    quote: "더 만든 게 아니에요. 버리지 않고 같이 먹은 겁니다.",
    image: "/juminjung/assets/cutscenes/noah-community-table-v1.png",
    imageAlt: "노아 그랜트가 낡은 JUJU HOTEL 식당의 긴 공동 식탁에 따뜻한 스튜를 나누고, 투숙객들이 객실 번호 대신 빈 의자에 둘러앉은 가운데 공개 배급 장부가 놓인 장면.",
  },
  {
    id: "thomas_microgrid_online",
    triggerStoryEventId: "thomas-grid",
    triggerStoryChoiceId: "microgrid",
    priority: 165,
    kicker: "JUJU HOTEL · INDEPENDENT POWER",
    title: "꺼지지 않는 세 개의 불빛",
    body: "Thomas가 마지막 차단기를 올리자 발전기실의 진동이 낮고 고른 박자로 바뀌었다. 벽을 따라 새로 묶은 배선은 진료 구역, 프런트 라디오, 동쪽 방벽의 표시등으로 갈라졌다. 객실 조명은 여전히 필요한 만큼만 켜졌지만, 어느 한쪽을 살리기 위해 다른 쪽을 완전히 포기할 필요는 없어졌다. 낡은 계기판의 바늘이 안정 구간에 머문 채 첫 밤의 부하를 견뎠다.",
    quote: "전기가 남은 게 아니에요. 낭비하던 전기를 되찾은 겁니다.",
    image: "/juminjung/assets/cutscenes/thomas-microgrid-online-v1.png",
    imageAlt: "토머스 리가 JUJU HOTEL 발전기실의 새 배전반을 올리고, 정돈된 배선이 진료 구역과 프런트 라디오, 동쪽 방벽 표시등으로 이어지는 가운데 계기판이 안정 구간을 가리키는 장면.",
  },
  {
    id: "hazel_perimeter_watch",
    triggerStoryEventId: "hazel-watch",
    triggerStoryChoiceId: "ranger",
    priority: 165,
    kicker: "JUJU HOTEL · OUTER PERIMETER",
    title: "괴물보다 먼저 울리는 종",
    body: "Hazel은 Vale가 표시한 이동로를 따라 철사와 빈 통, 프런트에서 떼어 낸 작은 황동 종을 호텔 외곽에 연결했다. 마지막 매듭을 당기자 동쪽 담장 끝에서 낮은 종소리가 차례로 돌아왔다. 그것은 괴물을 쓰러뜨리는 덫이 아니었다. 어둠이 철문에 닿기 전에 복도의 불을 깨우고, 잠든 사람들이 각자의 자리를 찾게 하는 경보였다.",
    quote: "이제 저것들이 먼저 우리를 보는 밤은 끝이야.",
    image: "/juminjung/assets/cutscenes/hazel-perimeter-watch-v1.png",
    imageAlt: "헤이즐 퀸이 비 내리는 JUJU HOTEL 외곽 담장에서 철사와 황동 종으로 만든 조기경보 장치를 점검하고, 멀리 따뜻한 호텔 창문과 안개 속 형체들이 보이는 장면.",
  },
  {
    id: "eleanor_clinic_opened",
    triggerStoryEventId: "eleanor-standard",
    triggerStoryChoiceId: "clinic",
    priority: 165,
    kicker: "JUJU HOTEL · MEDICAL CARE ZONE",
    title: "객실 하나가 진료소가 된 아침",
    body: "객실 문에서 황동 번호표를 떼어낸 자리에 흰 천 조각이 걸렸다. Eleanor는 남은 약품을 증상별로 나누고, 침대 두 개 사이에 진료 장부와 소독 도구를 놓았다. 복도에서 기다리던 사람들은 더는 아픈 몸을 숨긴 채 방을 구하지 않아도 되었다. JUJU HOTEL의 객실 하나가 잠자리 대신 매일 밤 사람을 살피는 상설 진료 구역이 되었다.",
    quote: "치료할 방이 생겼으니, 이제 늦기 전에 찾아낼 수 있어요.",
    image: "/juminjung/assets/cutscenes/eleanor-hotel-clinic-v1.png",
    imageAlt: "엘리너 리드가 낡은 JUJU HOTEL 객실을 개조한 작은 상설 진료소에서 약품과 진료 장부를 정리하고, 따뜻한 황동 램프 아래 붕대를 감은 환자를 살피는 장면.",
  },
  {
    id: "walter_archive_opened",
    triggerStoryEventId: "walter-key",
    triggerStoryChoiceId: "use_key",
    priority: 165,
    kicker: "BASEMENT ARCHIVE · FIRST ENTRY",
    title: "아버지가 잠가 둔 기록실",
    body: "황동 열쇠가 돌아가자 녹슨 잠금장치 안쪽에서 오래 붙어 있던 금속이 찢어지는 소리가 났다. Walter는 손전등으로 먼지 쌓인 장부와 릴 테이프, 도시 지도, 인간의 몸을 닮은 도해를 차례로 비췄다. 첫 장부에는 재난 전 발생 구역으로 옮겨진 호텔 발전기 부품과 진정제의 수량이 적혀 있었다. 그는 문턱을 넘지 않은 채 네 아버지 곁에서 이 방을 잠갔던 밤을 기억했다. 전원이 끊긴 라디오의 눈금은 91.3에 멈춰 있었고, 문이 열린 뒤 배관 깊은 곳에서 같은 금속성 마찰음이 한 번 되돌아왔다.",
    quote: "네 아버지가 감춘 건 비밀이 아니었다. 우리가 열 준비가 되지 않은 문이었다.",
    image: "/juminjung/assets/cutscenes/walter-basement-archive-v1.png",
    imageAlt: "월터 브릭스가 황동 열쇠와 손전등을 든 채 처음 열린 JUJU HOTEL 지하 기록실 문에 서 있고, 안쪽에 먼지 쌓인 장부와 릴 테이프, 라디오, 도시 지도와 생체 도해가 드러난 장면.",
  },
  {
    id: "mia_daniel_reunion",
    triggerStoryEventId: "mia-family",
    triggerStoryChoiceId: "reunite",
    priority: 160,
    kicker: "ROOM KEY 103 · FAMILY FOUND",
    title: "사진 속 두 사람이 다시 만난 밤",
    body: "다니엘은 미아가 품고 있던 토끼 인형의 찢어진 귀를 알아보았다. 미아는 곧장 달려가지 않았다. 비에 젖은 남자가 사진 속 아버지와 같은 목소리로 오래전 약속을 말할 때까지, 프런트의 황동 램프 아래에서 한 걸음씩 다가갔다. 다니엘이 무릎을 꿇자 아이의 손이 먼저 그의 얼굴에 닿았다.",
    quote: "방을 찾으러 온 두 사람은, 서로가 돌아갈 곳이라는 걸 가장 늦게 알았다.",
    image: "/juminjung/assets/cutscenes/mia-daniel-reunion-v1.png",
    imageAlt: "폭우가 내리는 낡은 JUJU HOTEL 복도에서 토끼 인형을 안은 미아가 한 손을 내밀고, 지친 다니엘이 무릎을 꿇어 조심스럽게 딸과 재회하는 장면.",
  },
  {
    id: "hotel_siege_held",
    triggerEventId: "hotel_siege",
    triggerChoiceId: "hold_lobby",
    priority: 150,
    kicker: "JUJU HOTEL · LOBBY DEFENSE",
    title: "호텔이 마지막 문이 된 밤",
    body: "유리벽이 안쪽으로 휘어질 때마다 황동 열쇠들이 한꺼번에 울렸다. 투숙객들은 프런트와 소파를 밀어 방어선을 세웠고, 남은 보안 물자와 부품을 바리케이드에 쏟았다. 선두에 선 한 사람이 쓰러진 뒤에야 폭우 속 형체들이 물러났다. 로비는 부서졌지만, 아침까지 호텔의 문은 안쪽에서 잠겨 있었다.",
    quote: "우리는 승리한 것이 아니라, 오늘 밤의 마지막 문을 지켰다.",
    image: "/juminjung/assets/cutscenes/hotel-siege-v1.png",
    imageAlt: "폭우와 번개 속 비인간적인 형체들이 JUJU HOTEL 로비 유리벽을 밀어붙이고, 생존자들이 바리케이드를 붙들며 부상자를 후송하고 손전등으로 방어하는 대규모 공성 장면.",
  },
  {
    id: "hotel_siege_retreat",
    triggerEventId: "hotel_siege",
    triggerChoiceId: "retreat_basement",
    priority: 150,
    kicker: "JUJU HOTEL · LOWER SHELTER",
    title: "로비를 내어주고 사람을 지켰다",
    body: "관리자는 객실 열쇠 대신 지하 방화문 열쇠를 들었다. 마지막 사람이 계단 아래로 사라지자 로비 유리벽이 무너졌고, 형체들은 프런트와 발전기 배선을 짓밟았다. 누구도 뒤에 남지 않았지만, 위층에서 들려오는 발소리는 호텔이 더는 완전한 피난처가 아니라는 사실을 밤새 되풀이했다.",
    quote: "건물은 다시 세울 수 있다. 하지만 오늘 포기한 층을 되찾으려면 또 다른 밤을 견뎌야 한다.",
    image: "/juminjung/assets/cutscenes/hotel-siege-v1.png",
    imageAlt: "폭우 속 비인간적인 형체들이 JUJU HOTEL 로비 유리벽을 돌파하려는 동안 생존자들이 지친 투숙객을 부축해 지하로 후퇴하고, 관리자가 마지막으로 방어선을 확인하는 장면.",
  },
  {
    id: "first_night",
    priority: 10,
    minimumCompletedDay: 1,
    maximumCompletedDay: 1,
    kicker: "FIRST NIGHT · 03:07 AM",
    title: "호텔이 숨을 죽인 시간",
    body: "마지막 순찰을 마치고 장부를 펼쳤지만, 적을 이름도 없이 식량과 연료만 셌다. 라디오는 같은 주파수를 맴돌았고 복도 끝의 문은 아까보다 조금 더 열려 있었다. 아버지가 없는 첫날 밤, 호텔의 모든 소리가 누군가의 발걸음처럼 들렸다.",
    quote: "아침까지 문을 지키는 것. 오늘 해야 할 일은 그것뿐이다.",
    image: "/juminjung/assets/cutscenes/first-night-v1.png",
    imageAlt: "낡은 JUJU HOTEL 프런트 장부와 라디오 너머로 비어 있는 어두운 복도가 길게 이어지는 첫날 밤.",
  },
  {
    id: "generator_blackout",
    triggerEventId: "generator_failure",
    triggerChoiceId: "blackout",
    priority: 140,
    kicker: "BLACKOUT · 02:41 AM",
    title: "호텔이 반쪽으로 어두워진 순간",
    body: "발전기가 마지막 기침을 토해내자 당신은 로비와 객실 한 동의 차단기를 내렸다. 황동 램프와 라디오가 동시에 죽었고, 붉은 비상등 몇 개만 복도 끝을 간신히 붙잡았다. 프런트의 손전등으로도 객실 열쇠 번호는 읽히지 않았다. 번개가 창을 가른 짧은 순간, 빗속의 그림자들이 창 바로 밖에 몰려든 모습이 드러났다.",
    quote: "어둠은 빈 공간이 아니었다. 우리가 보지 못하는 동안에도 무언가는 움직였다.",
    image: "/juminjung/assets/cutscenes/generator-blackout-v1.png",
    imageAlt: "발전기 출력이 부족해 전력을 차단한 낡은 호텔 로비에서 생존자들이 손전등과 붉은 비상등에 의지하고, 폭우가 치는 창 바로 밖에 여러 인영이 몰려든 장면.",
  },
  {
    id: "guest_attacked",
    triggerEventId: "perimeter_breach",
    triggerChoiceId: "fight",
    priority: 150,
    kicker: "BREACH · FRONT LOBBY",
    title: "쓰러진 사람, 남겨진 열쇠",
    body: "철문이 안쪽으로 꺾이자 투숙객 한 명이 무너진 현관 쪽으로 뛰어들었다. 한 번의 충돌 뒤 그는 피와 빗물을 끌며 프런트 뒤로 돌아왔고, 다른 생존자가 그의 어깨를 붙잡아 카운터 아래로 끌어내렸다. 깨진 유리 너머의 형체는 쓰러진 사람을 쫓지 않았다. 기울어진 고개는 카운터의 황동 열쇠들을 향하고 있었다.",
    quote: "문을 막은 건 사람이었지만, 저것이 찾은 건 사람이 아니었다.",
    image: "/juminjung/assets/cutscenes/hotel-breach-guest-attack-v1.png",
    imageAlt: "파손된 호텔 로비에서 한 생존자가 프런트 카운터 뒤의 부상자를 끌어내고, 폭우 속 괴물 형체가 무너진 바리케이드 너머에 서 있는 장면.",
  },
  {
    id: "first_monster_sighting",
    triggerEventId: "perimeter_breach",
    priority: 100,
    kicker: "FIRST SIGHTING · EAST GATE",
    title: "철문 너머에 서 있던 것",
    body: "번개가 로비를 하얗게 가른 순간, 빗속의 형체가 사람보다 한 뼘 더 길게 몸을 폈다. 그것은 문을 두드리지 않았다. 손가락 하나로 휘어진 철문을 천천히 짚었고, 라디오에서는 아버지의 주파수와 같은 잡음이 흘렀다.",
    quote: "사람처럼 보인다고 해서 전부 들이지는 마.",
    image: "/juminjung/assets/cutscenes/first-monster-sighting-v1.png",
    imageAlt: "차가운 빗속에서 비정상적으로 긴 괴물이 JUJU HOTEL의 휘어진 철문 너머에 서 있는 첫 목격 장면.",
  },
  {
    id: "room_body_discovery",
    triggerEventId: "room_body_discovery",
    priority: 130,
    kicker: "ROOM 207 · 05:18 AM",
    title: "안에서 잠긴 객실",
    body: "마스터키로 207호를 열자 빗물 냄새보다 먼저 오래된 피와 젖은 석회의 냄새가 밀려왔다. 시신은 침대 시트 아래에 있었고 황동 열쇠는 문 안쪽 바닥에 놓여 있었다. 검은 흔적은 시신 앞에서 시작해 깨진 창문에서 끝났다. 누군가 들어온 흔적은 없었지만, 무언가는 이 방에서 나간 뒤였다.",
    quote: "문은 밤새 잠겨 있었다. 그렇다면 우리가 잠근 것은 무엇이었을까.",
    image: "/juminjung/assets/cutscenes/room-207-body-discovery-v1.png",
    imageAlt: "비 내리는 새벽의 낡은 JUJU HOTEL 207호에서 두 생존자가 시트로 완전히 덮인 시신과 창가에서 이어진 검은 흔적, 바닥의 황동 열쇠를 발견한 장면.",
  },
  {
    id: "father_radio_signal",
    triggerEventId: "father_radio_signal",
    priority: 120,
    kicker: "91.3 MHz · 01:13 AM",
    title: "죽어 있던 주파수의 목소리",
    body: "잡음 사이로 아버지만 쓰던 호출명이 세 번 반복됐다. 목소리는 대답하지 말라는 경고와 함께 서로 다른 세 중계기의 좌표를 차례로 읽었다. 지도에서 초록색 호텔 표식과 세 붉은 송신점을 연결하자, 붉은 삼각형은 호텔이 아니라 재난 최초 발생 구역을 에워쌌다. 세 송신기가 같은 기억을 되풀이하는 덫인지, 아버지가 자신의 위치를 숨긴 구조 신호인지는 아직 알 수 없었다.",
    quote: "그 목소리는 집으로 돌아오겠다고 하지 않았다. 먼저 자신을 찾아내라고 했다.",
    image: "/juminjung/assets/cutscenes/father-radio-signal-v1.png",
    imageAlt: "폭우가 내리는 JUJU HOTEL 프런트에서 두 생존자가 갑자기 켜진 낡은 라디오와 세 송신 지점을 표시한 도시 지도를 바라보고, 깨진 창밖의 긴 그림자를 경계하는 장면.",
  },
  {
    id: "father_at_gate_quarantine",
    triggerEventId: "father_at_gate",
    triggerChoiceId: "quarantine_verify",
    priority: 125,
    kicker: "EAST GATE · QUARANTINE",
    title: "기억은 같고, 피는 달랐다",
    body: "그는 아버지와 나만 알던 세 가지 질문에 모두 답했다. 그러나 철문 아래로 밀어 넣은 혈액 표본은 인간의 체온에서 굳지 않았고, Vale의 시약은 검은 고리처럼 번졌다. 경비는 철문을 잠근 채 바깥 격리선을 세웠다. 아버지의 기억이 돌아온 것인지, 기억만 돌아온 것인지는 아직 말할 수 없었다.",
    quote: "목소리는 아버지였다. 표본은 아니었다.",
    image: "/juminjung/assets/cutscenes/father-at-gate-v1.png",
    imageAlt: "폭우 속 JUJU HOTEL의 잠긴 철문 밖에 낡은 가방을 든 중년 남성이 서 있고, 안쪽의 젊은 관리자가 황동 마스터키를 쥔 채 검증용 트레이와 등불 너머로 그를 경계하는 장면.",
  },
  {
    id: "father_at_gate_opened",
    triggerEventId: "father_at_gate",
    triggerChoiceId: "open_gate",
    priority: 125,
    kicker: "EAST GATE · ADMIT ONE",
    title: "황동 열쇠가 돌아가기 직전",
    body: "그는 가방을 열어 아버지만 알던 발전기 부품과 봉인 연료를 바닥에 내려놓았다. 세 가지 기억도 틀리지 않았다. 경비가 물러나고 황동 열쇠가 자물쇠에 닿자, 복도의 투숙객들은 숨을 죽였다. 사람을 들이는 규칙을 지켜 온 호텔은 이번 한 번만 신원보다 기억을 먼저 믿기로 했다.",
    quote: "문이 열린 뒤에야, 나는 우리가 누구를 맞이했는지 다시 묻게 되었다.",
    image: "/juminjung/assets/cutscenes/father-at-gate-v1.png",
    imageAlt: "폭우 속 JUJU HOTEL의 잠긴 철문 밖에 발전기 물자가 든 가방을 내려놓은 중년 남성이 서 있고, 안쪽의 젊은 관리자가 문을 열기 직전 황동 마스터키를 쥔 장면.",
  },
  {
    id: "refugees_sheltered",
    triggerEventId: "refugee_wave",
    triggerChoiceId: "shelter",
    priority: 80,
    minimumCompletedDay: 8,
    kicker: "THE TURNING KEY · EAST GATE",
    title: "철문을 여는 손",
    body: "젖은 얼굴들이 철창 너머에서 대답을 기다렸다. 아이의 기침이 다시 들리자 당신은 바리케이드의 빗장을 풀고 황동 열쇠를 돌렸다. 문이 열리는 몇 분 동안 바깥의 그림자도 호텔을 보았지만, 오늘 밤 JUJU HOTEL은 다시 사람이 사는 곳이 될 것이다.",
    quote: "방은 없어도, 지붕은 나눌 수 있다.",
    image: "/juminjung/assets/cutscenes/refugees-at-gate-v1.png",
    imageAlt: "차가운 폭우 속에서 아이를 안은 보호자와 노인 등 피난민들이 JUJU HOTEL 철문 앞에 모여 도움을 청하는 장면.",
  },
  {
    id: "refugees_denied",
    triggerEventId: "refugee_wave",
    triggerChoiceId: "deny",
    priority: 80,
    minimumCompletedDay: 8,
    kicker: "THE CLOSED GATE · EAST GATE",
    title: "철문 밖에 남은 발자국",
    body: "램프를 끄자 바깥의 얼굴들이 하나씩 어둠에 잠겼다. 아이의 기침 소리는 빗소리에 묻힐 때까지 오래 남았다. 새벽이 왔을 때 철문 앞에는 작은 신발 자국과, 호텔 쪽을 향해 눌린 손바닥 자국만 남아 있었다.",
    quote: "문을 지켰다. 그러나 무엇을 지킨 것인지는 장부에 적히지 않았다.",
    image: "/juminjung/assets/cutscenes/refugees-at-gate-v1.png",
    imageAlt: "차가운 폭우 속에서 아이를 안은 보호자와 노인 등 피난민들이 JUJU HOTEL 철문 앞에 모여 도움을 청하는 장면.",
  },
];

export function getCutscene(id: string | null): CutsceneDefinition | null {
  return CUTSCENES.find((cutscene) => cutscene.id === id) ?? null;
}
