import type { NightEventDefinition } from "./types.ts";

export const NIGHT_EVENTS: NightEventDefinition[] = [
  { id: "perimeter_breach", title: "동쪽 철문의 그림자", description: "철문 바깥의 무언가가 바리케이드를 밀어내고 있습니다.", quote: "금속이 한 번 휘고, 복도 조명이 모두 꺼졌다.", priority: 100, condition: { worldStates: ["COLLAPSE", "CRITICAL", "END_STAGE"], minimumThreat: 20, maximumSecurity: 59, requiresGuests: true }, choices: [
    { id: "barricade", label: "부품으로 철문을 보강한다", description: "부품 2를 사용해 침입을 늦춥니다.", requiredResources: { parts: 2 }, effect: { resources: { parts: -2 }, hotelStats: { hotelCondition: -2, security: 3 }, threat: -5 } },
    { id: "fight", label: "무장 인원을 내보낸다", description: "위협은 크게 줄지만 투숙객 한 명이 다칠 수 있습니다.", effect: { resources: { security: -5 }, reputations: { military: 5 }, threat: -10, targetGuestHealth: -15 } },
  ] },
  { id: "owen_hayes_standoff", title: "복도의 군화", description: "가까운 객실에 배치된 Owen과 Hayes가 계단참에서 총구를 겨눕니다.", quote: "‘이 호텔의 규칙이 군의 명령보다 위인가?’", priority: 95, condition: { forbiddenFlags: ["owen_hayes_standoff_resolved"], relationship: { sourceId: "owen", targetId: "hayes", maximumWeightedValue: -120 } }, choices: [
    { id: "separate", label: "두 사람을 직접 떼어 놓는다", description: "중재로 충돌을 늦추고 객실 재배치를 요구합니다.", effect: { hotelStats: { security: -2 }, flags: { owen_hayes_standoff_resolved: true }, guestEffects: [{ guestId: "owen", stress: -5 }, { guestId: "hayes", trust: -5 }], relationshipChanges: [{ sourceId: "owen", targetId: "hayes", delta: 15, type: "ENEMY" }, { sourceId: "hayes", targetId: "owen", delta: 15, type: "ENEMY" }] } },
    { id: "arm_owen", label: "Owen에게 무기를 돌려준다", description: "보안 물자 4를 사용해 군의 압박에 맞서지만 적대가 깊어집니다.", requiredResources: { security: 4 }, effect: { resources: { security: -4 }, hotelStats: { security: 5 }, reputations: { military: -5, refugee: 4 }, flags: { owen_hayes_standoff_resolved: true, military_resistance_started: true }, guestEffects: [{ guestId: "owen", trust: 10 }, { guestId: "hayes", trust: -10 }], relationshipChanges: [{ sourceId: "owen", targetId: "hayes", delta: -10, type: "ENEMY" }, { sourceId: "hayes", targetId: "owen", delta: -10, type: "ENEMY" }] } },
  ] },
  { id: "room_body_discovery", title: "207호의 새벽", description: "잠겨 있던 207호에서 연락이 끊긴 생존자의 시신과 창가로 이어진 검은 흔적이 발견됩니다.", quote: "황동 열쇠는 문 안쪽에 있었고, 검은 흔적은 시신 앞에서 창문까지 이어졌다.", priority: 92, condition: { minimumDay: 10, minimumThreat: 12, maximumSecurity: 55, requiresGuests: true, forbiddenFlags: ["room_body_discovery_resolved"] }, choices: [
    { id: "seal_room", label: "207호를 봉쇄하고 흔적을 태운다", description: "연료와 부품을 사용해 오염 가능성을 차단하지만 진실을 알 기회를 잃습니다.", requiredResources: { fuel: 2, parts: 1 }, effect: { resources: { fuel: -2, parts: -1 }, hotelStats: { security: 3 }, reputations: { community: -2 }, flags: { room_body_discovery_resolved: true, room_207_sealed: true }, threat: -4, allGuestStress: 3 } },
    { id: "investigate_body", label: "시신과 객실을 조사한다", description: "위험을 감수해 괴물의 침입 방식에 관한 증거를 확보합니다.", effect: { hotelStats: { security: -2 }, reputations: { community: 2 }, flags: { room_body_discovery_resolved: true, room_207_investigated: true, monster_room_entry_clue: true }, threat: 3, allGuestStress: 6 } },
  ] },
  { id: "food_shortage", title: "배급실 앞의 언쟁", description: "남은 식량이 오늘 밤 투숙객 모두에게 돌아가지 않습니다.", quote: "빈 통조림이 바닥을 구르자 복도에서 말소리가 끊겼다.", priority: 90, condition: { shortage: "food", requiresGuests: true }, choices: [
    { id: "ration", label: "배급량을 줄인다", description: "자원은 보존하지만 모두의 Stress가 증가합니다.", effect: { allGuestStress: 8, reputations: { community: -3 } } },
    { id: "share", label: "비상 식량을 연다", description: "식량 3을 더 소비하고 공동체의 신뢰를 지킵니다.", requiredResources: { food: 3 }, effect: { resources: { food: -3 }, allGuestStress: -3, reputations: { humanitarian: 5, community: 3 } } },
  ] },
  { id: "generator_failure", title: "발전기의 마지막 기침", description: "연료 압력이 떨어지며 호텔 절반이 암흑에 잠깁니다.", quote: "아버지가 남긴 발전기 매뉴얼의 마지막 장이 찢겨 있다.", priority: 80, condition: { maximumResource: { fuel: 10 } }, choices: [
    { id: "reserve", label: "예비 연료를 붓는다", description: "연료 2를 더 사용해 조명을 유지합니다.", requiredResources: { fuel: 2 }, effect: { resources: { fuel: -2 }, threat: -1 } },
    { id: "blackout", label: "로비와 객실 한 동의 전력을 끊는다", description: "남은 발전기 출력을 보존하지만 호텔 상태와 안전이 나빠집니다.", effect: { hotelStats: { hotelCondition: -3, security: -3 }, flags: { generator_blackout: true }, threat: 5 } },
  ] },
  { id: "lily_vale_breakthrough", title: "두 방 사이의 증거", description: "가까이 배치된 Lily와 Vale가 밤새 기록과 조직 샘플을 대조해 공통 패턴을 찾아냅니다.", quote: "‘문서의 날짜와 세포 분열 주기가 정확히 일치해요.’", priority: 75, condition: { forbiddenFlags: ["lily_vale_relationship_event"], relationship: { sourceId: "lily", targetId: "vale", minimumWeightedValue: 30 } }, choices: [
    { id: "shared_lab", label: "공동 조사실을 허가한다", description: "부품 1을 사용해 두 사람의 협업과 정보망을 강화합니다.", requiredResources: { parts: 1 }, effect: { resources: { parts: -1 }, reputations: { community: 3 }, flags: { lily_vale_relationship_event: true, investigation_network_active: true }, guestEffects: [{ guestId: "lily", trust: 6 }, { guestId: "vale", trust: 6 }], relationshipChanges: [{ sourceId: "lily", targetId: "vale", delta: 15, type: "INVESTIGATION" }, { sourceId: "vale", targetId: "lily", delta: 15, type: "INVESTIGATION" }] } },
    { id: "separate_evidence", label: "증거를 서로 다른 금고에 둔다", description: "연구를 분리해 보안은 높이지만 협력은 약해집니다.", effect: { hotelStats: { security: 3 }, flags: { lily_vale_relationship_event: true }, relationshipChanges: [{ sourceId: "lily", targetId: "vale", delta: -10, type: "INVESTIGATION" }, { sourceId: "vale", targetId: "lily", delta: -10, type: "INVESTIGATION" }] } },
  ] },
  { id: "medical_shift", title: "새벽 진료 교대", description: "가까운 객실의 Eleanor와 Ruth가 부상자 치료 순서를 두고 당신의 결정을 기다립니다.", quote: "‘같이하면 더 살릴 수 있어요. 대신 약이 더 필요합니다.’", priority: 70, condition: { forbiddenFlags: ["medical_relationship_event"], relationship: { sourceId: "eleanor", targetId: "ruth", minimumWeightedValue: 60 } }, choices: [
    { id: "joint_triage", label: "공동 진료를 승인한다", description: "의약품 1을 사용해 두 의료인의 유대와 건강을 회복합니다.", requiredResources: { medicine: 1 }, effect: { resources: { medicine: -1 }, reputations: { humanitarian: 4 }, flags: { medical_relationship_event: true, medical_joint_triage: true }, guestEffects: [{ guestId: "eleanor", health: 8, trust: 5 }, { guestId: "ruth", health: 8, trust: 5 }], relationshipChanges: [{ sourceId: "eleanor", targetId: "ruth", delta: 10, type: "ALLY" }, { sourceId: "ruth", targetId: "eleanor", delta: 10, type: "ALLY" }] } },
    { id: "split_shift", label: "각자 맡은 층만 치료하게 한다", description: "약품을 아끼고 피로를 낮추지만 협업은 약해집니다.", effect: { flags: { medical_relationship_event: true, medical_split_shift: true }, guestEffects: [{ guestId: "eleanor", stress: -5 }, { guestId: "ruth", stress: -5 }], relationshipChanges: [{ sourceId: "eleanor", targetId: "ruth", delta: -5, type: "ALLY" }, { sourceId: "ruth", targetId: "eleanor", delta: -5, type: "ALLY" }] } },
  ] },
  { id: "refugee_wave", title: "빗속의 가족들", description: "어린아이를 포함한 피난민들이 철문 앞에서 하룻밤만을 청합니다.", quote: "‘방은 필요 없어요. 지붕만이라도 빌려주세요.’", priority: 60, condition: { worldStates: ["UNREST", "COLLAPSE", "CRITICAL", "END_STAGE"], minimumDay: 8, dayModulo: 4 }, choices: [
    { id: "shelter", label: "로비를 피난처로 연다", description: "식량을 나누고 피난민 평판을 얻지만 위협도 따라옵니다.", requiredResources: { food: 4, water: 3 }, effect: { resources: { food: -4, water: -3 }, reputations: { refugee: 8, humanitarian: 6, community: 3 }, flags: { refugees_sheltered: true, refugees_denied: false }, threat: 4 } },
    { id: "deny", label: "철문을 열지 않는다", description: "안전은 유지되지만 바깥에 소문이 퍼집니다.", effect: { reputations: { refugee: -8, humanitarian: -4 }, hotelStats: { security: 2 }, flags: { refugees_denied: true, refugees_sheltered: false }, threat: -1 } },
  ] },
  { id: "quiet_watch", title: "긴 복도, 짧은 밤", description: "라디오 잡음 외에는 아무 소리도 들리지 않습니다.", quote: "평온한 밤일수록 다음 노크가 더 선명하게 들린다.", priority: 0, condition: {}, choices: [
    { id: "patrol", label: "복도를 순찰한다", description: "연료 1을 사용해 Security를 높이고 위협을 낮춥니다.", requiredResources: { fuel: 1 }, effect: { resources: { fuel: -1, security: 2 }, hotelStats: { security: 2 }, threat: -2 } },
    { id: "rest", label: "모두 쉬게 한다", description: "투숙객들의 Stress가 조금 회복됩니다.", effect: { allGuestStress: -5 } },
  ] },
];
