import type { NightEventDefinition } from "./types.ts";

export const NIGHT_EVENTS: NightEventDefinition[] = [
  { id: "hotel_siege", title: "JUJU HOTEL 공성", description: "폭우 속에서 몰려든 형체들이 로비 유리벽과 모든 출입구를 동시에 밀어붙입니다.", quote: "철문 하나를 두드리던 밤은 끝났다. 이번에는 호텔 전체가 문이 되었다.", priority: 115, condition: { worldStates: ["CRITICAL", "END_STAGE"], minimumDay: 25, minimumThreat: 45, maximumSecurity: 74, requiresGuests: true, forbiddenFlags: ["hotel_siege_resolved"] }, choices: [
    { id: "hold_lobby", label: "로비 방어선을 끝까지 지킨다", description: "보안 물자 6과 부품 3으로 바리케이드를 보강합니다. 침입은 격퇴하지만 방어선의 투숙객 한 명이 중상을 입고 모두가 충격을 받습니다.", requiredResources: { security: 6, parts: 3 }, effect: { resources: { security: -6, parts: -3 }, hotelStats: { hotelCondition: -5, security: 5 }, reputations: { military: 8, community: 4 }, flags: { hotel_siege_resolved: true, hotel_siege_repelled: true }, threat: -18, allGuestStress: 6, targetGuestHealth: -20, targetGuestHealthMinimum: 1 } },
    { id: "retreat_basement", label: "생활층을 버리고 지하로 후퇴한다", description: "사람을 우선해 지하 방화문으로 철수합니다. 부상은 피하지만 로비와 방어 시설이 크게 파괴됩니다.", effect: { hotelStats: { hotelCondition: -15, security: -10 }, reputations: { community: 5, humanitarian: 3 }, flags: { hotel_siege_resolved: true, hotel_siege_breached: true }, threat: 8, allGuestStress: 12 } },
  ] },
  { id: "perimeter_breach", title: "동쪽 철문의 그림자", description: "철문 바깥의 무언가가 바리케이드를 밀어내고 있습니다.", quote: "금속이 한 번 휘고, 복도 조명이 모두 꺼졌다.", priority: 100, condition: { worldStates: ["COLLAPSE", "CRITICAL", "END_STAGE"], minimumThreat: 20, maximumSecurity: 59, requiresGuests: true }, choices: [
    { id: "barricade", label: "부품으로 철문을 보강한다", description: "부품 2를 사용해 침입을 늦춥니다.", requiredResources: { parts: 2 }, effect: { resources: { parts: -2 }, hotelStats: { hotelCondition: -2, security: 3 }, threat: -5 } },
    { id: "fight", label: "무장 인원을 내보낸다", description: "위협은 크게 줄지만 투숙객 한 명이 다칠 수 있습니다.", effect: { resources: { security: -5 }, reputations: { military: 5 }, threat: -10, targetGuestHealth: -15 } },
  ] },
  { id: "owen_hayes_standoff", title: "복도의 군화", description: "가까운 객실에 배치된 Owen과 Hayes가 계단참에서 총구를 겨눕니다.", quote: "‘이 호텔의 규칙이 군의 명령보다 위인가?’", priority: 95, condition: { forbiddenFlags: ["owen_hayes_standoff_resolved"], relationship: { sourceId: "owen", targetId: "hayes", maximumWeightedValue: -120 } }, choices: [
    { id: "separate", label: "두 사람을 직접 떼어 놓는다", description: "중재로 충돌을 늦추고 객실 재배치를 요구합니다.", effect: { hotelStats: { security: -2 }, flags: { owen_hayes_standoff_resolved: true }, guestEffects: [{ guestId: "owen", stress: -5 }, { guestId: "hayes", trust: -5 }], relationshipChanges: [{ sourceId: "owen", targetId: "hayes", delta: 15, type: "ENEMY" }, { sourceId: "hayes", targetId: "owen", delta: 15, type: "ENEMY" }] } },
    { id: "arm_owen", label: "Owen에게 무기를 돌려준다", description: "보안 물자 4를 사용해 군의 압박에 맞서지만 적대가 깊어집니다.", requiredResources: { security: 4 }, effect: { resources: { security: -4 }, hotelStats: { security: 5 }, reputations: { military: -5, refugee: 4 }, flags: { owen_hayes_standoff_resolved: true, military_resistance_started: true }, guestEffects: [{ guestId: "owen", trust: 10 }, { guestId: "hayes", trust: -10 }], relationshipChanges: [{ sourceId: "owen", targetId: "hayes", delta: -10, type: "ENEMY" }, { sourceId: "hayes", targetId: "owen", delta: -10, type: "ENEMY" }] } },
  ] },
  { id: "father_at_gate", title: "철문 밖의 아버지", description: "무전에 응답한 뒤, 아버지의 얼굴과 목소리를 가진 남자가 잠긴 철문 앞에 섰습니다.", quote: "‘문을 열기 전에 물어봐라. 네가 기억하는 나와 내가 기억하는 네가 같은지.’", priority: 98, condition: { minimumDay: 24, requiredFlags: { father_return_route: true }, forbiddenFlags: ["father_return_encounter_resolved"] }, choices: [
    { id: "quarantine_verify", label: "철문 밖에서 혈액과 기억을 검증한다", description: "의약품과 탄약 등 보안 물자를 사용해 격리를 유지하고, 기억은 맞지만 인간과 다른 생체 표본을 확보합니다.", requiredResources: { medicine: 1, security: 2 }, effect: { resources: { medicine: -1, security: -2 }, hotelStats: { security: 2 }, flags: { father_return_encounter_resolved: true, father_return_quarantined: true, father_memory_test_passed: true, father_sample_anomalous: true, monster_origin_clue_2: true }, fatherStoryProgress: 15, threat: -2 } },
    { id: "open_gate", label: "목소리를 믿고 철문을 연다", description: "그가 가져온 발전기 물자와 재회의 가능성을 받아들이지만, 정체를 확인하지 못한 존재를 호텔에 들입니다.", effect: { resources: { fuel: 4, parts: 3 }, hotelStats: { security: -5 }, flags: { father_return_encounter_resolved: true, father_return_admitted: true, father_reunion_possible: true }, fatherStoryProgress: 25, threat: 15, allGuestStress: 10 } },
  ] },
  { id: "room_body_discovery", title: "207호의 새벽", description: "비어 있어야 할 207호에서 신원 미상의 시신과 창가로 이어진 검은 흔적이 발견됩니다.", quote: "황동 열쇠는 문 안쪽에 있었고, 검은 흔적은 시신 앞에서 창문까지 이어졌다.", priority: 92, condition: { minimumDay: 10, minimumThreat: 12, maximumSecurity: 55, requiresGuests: true, requiredEmptyRoomNumber: 207, forbiddenFlags: ["room_body_discovery_resolved"] }, choices: [
    { id: "seal_room", label: "207호를 봉쇄하고 흔적을 태운다", description: "연료와 부품을 사용해 오염 가능성을 차단하지만 객실을 다시 복구해야 합니다.", requiredResources: { fuel: 2, parts: 1 }, effect: { resources: { fuel: -2, parts: -1 }, hotelStats: { security: 3 }, reputations: { community: -2 }, flags: { room_body_discovery_resolved: true, room_207_sealed: true }, threat: -4, allGuestStress: 3, roomChange: { roomNumber: 207, status: "LOCKED", roomCondition: 55 } } },
    { id: "investigate_body", label: "시신과 객실을 조사한다", description: "위험을 감수해 증거를 확보하지만 훼손된 객실은 복구 전까지 사용할 수 없습니다.", effect: { hotelStats: { security: -2 }, reputations: { community: 2 }, flags: { room_body_discovery_resolved: true, room_207_investigated: true, monster_room_entry_clue: true }, threat: 3, allGuestStress: 6, roomChange: { roomNumber: 207, status: "DAMAGED", roomCondition: 35 } } },
  ] },
  { id: "food_shortage", title: "배급실 앞의 언쟁", description: "남은 식량이 오늘 밤 투숙객 모두에게 돌아가지 않습니다.", quote: "빈 통조림이 바닥을 구르자 복도에서 말소리가 끊겼다.", priority: 90, condition: { shortage: "food", requiresGuests: true }, choices: [
    { id: "ration", label: "배급량을 줄인다", description: "자원은 보존하지만 모두의 Stress가 증가합니다.", effect: { allGuestStress: 8, reputations: { community: -3 } } },
    { id: "share", label: "비상 식량을 연다", description: "식량 3을 더 소비하고 공동체의 신뢰를 지킵니다.", requiredResources: { food: 3 }, effect: { resources: { food: -3 }, allGuestStress: -3, reputations: { humanitarian: 5, community: 3 } } },
  ] },
  { id: "truth_responses", title: "증언이 돌아오는 주파수", description: "Lily가 공개한 기록을 들은 생존자들이 서로 다른 지역에서 같은 형체와 실종 패턴을 송신해 옵니다.", quote: "잡음 사이의 목소리들은 서로 만난 적이 없었지만, 모두 같은 문을 기억하고 있었다.", priority: 84, condition: { minimumDay: 16, requiredFlags: { lily_documents_decoded: true, lily_truth_broadcast: true }, forbiddenFlags: ["lily_truth_archived", "truth_responses_resolved"] }, choices: [
    { id: "receive_testimonies", label: "발전기를 더 돌려 증언을 대조한다", description: "연료 1을 사용해 원격 증언과 좌표를 검증합니다. 괴물 기원의 보강 증거를 얻지만 호텔 위치가 더 넓게 노출됩니다.", requiredResources: { fuel: 1 }, effect: { resources: { fuel: -1, parts: 1 }, reputations: { community: 4, humanitarian: 5 }, flags: { truth_responses_resolved: true, survivor_testimonies_verified: true, monster_origin_clue_2: true }, fatherStoryProgress: 10, threat: 5 } },
    { id: "close_frequency", label: "주파수를 닫고 수신 기록만 봉인한다", description: "추가 송신을 중단해 위치 노출을 줄이지만, 바깥 생존자들의 증언을 검증할 기회를 포기합니다.", effect: { hotelStats: { security: 3 }, reputations: { humanitarian: -3 }, flags: { truth_responses_resolved: true, truth_frequency_closed: true }, threat: -5 } },
  ] },
  { id: "generator_failure", title: "발전기의 마지막 기침", description: "연료 압력이 떨어지며 호텔 절반이 암흑에 잠깁니다.", quote: "아버지가 남긴 발전기 매뉴얼의 마지막 장이 찢겨 있다.", priority: 80, condition: { maximumResource: { fuel: 10 }, forbiddenFlags: ["generator_network_stable"] }, choices: [
    { id: "reserve", label: "예비 연료를 붓는다", description: "연료 2를 더 사용해 조명을 유지합니다.", requiredResources: { fuel: 2 }, effect: { resources: { fuel: -2 }, threat: -1 } },
    { id: "blackout", label: "로비와 객실 한 동의 전력을 끊는다", description: "남은 발전기 출력을 보존하지만 호텔 상태와 안전이 나빠집니다.", effect: { hotelStats: { hotelCondition: -3, security: -3 }, flags: { generator_blackout: true }, threat: 5 } },
  ] },
  { id: "father_radio_signal", title: "아버지의 주파수", description: "오래 끊겼던 91.3MHz에서 아버지만 쓰던 호출명과 서로 다른 세 송신 좌표가 반복됩니다.", quote: "‘주주, 들리면 대답하지 마라. 먼저 내가 있는 곳을 찾아.’", priority: 85, condition: { minimumDay: 20, requiredFlags: { father_secret_discovered: true }, forbiddenFlags: ["father_radio_signal_resolved"] }, choices: [
    { id: "trace_signal", label: "응답하지 않고 신호를 역추적한다", description: "연료와 부품을 사용해 세 중계기를 역추적하고 괴물 기원의 핵심 증거를 확보합니다.", requiredResources: { fuel: 2, parts: 1 }, effect: { resources: { fuel: -2, parts: -1 }, flags: { father_radio_signal_resolved: true, father_signal_traced: true, monster_origin_clue_2: true }, fatherStoryProgress: 15, threat: 2 } },
    { id: "answer_signal", label: "아버지의 호출명으로 응답한다", description: "귀환 가능성을 열지만 호텔 위치가 노출되어 위협과 모든 투숙객의 불안이 크게 증가합니다.", effect: { hotelStats: { security: -3 }, flags: { father_radio_signal_resolved: true, father_signal_answered: true, father_return_route: true }, fatherStoryProgress: 20, threat: 12, allGuestStress: 8 } },
  ] },
  { id: "lily_vale_breakthrough", title: "두 방 사이의 증거", description: "가까이 배치된 Lily와 Vale가 밤새 기록과 조직 샘플을 대조해 공통 패턴을 찾아냅니다.", quote: "‘문서의 날짜와 세포 분열 주기가 정확히 일치해요.’", priority: 75, condition: { forbiddenFlags: ["lily_vale_relationship_event"], relationship: { sourceId: "lily", targetId: "vale", minimumWeightedValue: 30 } }, choices: [
    { id: "shared_lab", label: "공동 조사실을 허가한다", description: "부품 1을 사용해 두 사람의 협업과 정보망을 강화합니다.", requiredResources: { parts: 1 }, effect: { resources: { parts: -1 }, reputations: { community: 3 }, flags: { lily_vale_relationship_event: true, investigation_network_active: true }, guestEffects: [{ guestId: "lily", trust: 6 }, { guestId: "vale", trust: 6 }], relationshipChanges: [{ sourceId: "lily", targetId: "vale", delta: 15, type: "INVESTIGATION" }, { sourceId: "vale", targetId: "lily", delta: 15, type: "INVESTIGATION" }] } },
    { id: "separate_evidence", label: "증거를 서로 다른 금고에 둔다", description: "연구를 분리해 보안은 높이지만 협력은 약해집니다.", effect: { hotelStats: { security: 3 }, flags: { lily_vale_relationship_event: true }, relationshipChanges: [{ sourceId: "lily", targetId: "vale", delta: -10, type: "INVESTIGATION" }, { sourceId: "vale", targetId: "lily", delta: -10, type: "INVESTIGATION" }] } },
  ] },
  { id: "medical_shift", title: "새벽 진료 교대", description: "가까운 객실의 Eleanor와 Ruth가 부상자 치료 순서를 두고 당신의 결정을 기다립니다.", quote: "‘같이하면 더 살릴 수 있어요. 대신 약이 더 필요합니다.’", priority: 70, condition: { forbiddenFlags: ["medical_relationship_event"], relationship: { sourceId: "eleanor", targetId: "ruth", minimumWeightedValue: 60 } }, choices: [
    { id: "joint_triage", label: "공동 진료를 승인한다", description: "의약품 1을 사용해 두 의료인의 유대와 건강을 회복합니다.", requiredResources: { medicine: 1 }, effect: { resources: { medicine: -1 }, reputations: { humanitarian: 4 }, flags: { medical_relationship_event: true, medical_joint_triage: true }, guestEffects: [{ guestId: "eleanor", health: 8, trust: 5 }, { guestId: "ruth", health: 8, trust: 5 }], relationshipChanges: [{ sourceId: "eleanor", targetId: "ruth", delta: 10, type: "ALLY" }, { sourceId: "ruth", targetId: "eleanor", delta: 10, type: "ALLY" }] } },
    { id: "split_shift", label: "각자 맡은 층만 치료하게 한다", description: "약품을 아끼고 피로를 낮추지만 협업은 약해집니다.", effect: { flags: { medical_relationship_event: true, medical_split_shift: true }, guestEffects: [{ guestId: "eleanor", stress: -5 }, { guestId: "ruth", stress: -5 }], relationshipChanges: [{ sourceId: "eleanor", targetId: "ruth", delta: -5, type: "ALLY" }, { sourceId: "ruth", targetId: "eleanor", delta: -5, type: "ALLY" }] } },
  ] },
  { id: "refugee_wave", title: "빗속의 가족들", description: "어린아이를 포함한 피난민들이 철문 앞에서 하룻밤만을 청합니다.", quote: "‘방은 필요 없어요. 지붕만이라도 빌려주세요.’", priority: 60, condition: { worldStates: ["UNREST", "COLLAPSE", "CRITICAL", "END_STAGE"], minimumDay: 8, dayModulo: 4 }, choices: [
    { id: "shelter", label: "로비를 피난처로 연다", description: "식량을 나누고 피난민 평판을 얻지만 위협도 따라옵니다.", requiredResources: { food: 4, water: 3 }, effect: { resources: { food: -4, water: -3 }, reputations: { refugee: 8, humanitarian: 6, community: 3 }, flags: { refugees_sheltered: true, refugees_denied: false }, threat: 4 } },
    { id: "deny", label: "철문을 열지 않는다", description: "안전은 유지되지만 바깥에 소문이 퍼집니다.", effect: { reputations: { refugee: -8, humanitarian: -4 }, hotelStats: { security: 2 }, flags: { refugees_denied: true, refugees_sheltered: false }, threat: -1 } },
  ] },
  { id: "quiet_watch", title: "긴 복도, 짧은 밤", description: "라디오 잡음 외에는 아무 소리도 들리지 않습니다.", quote: "평온한 밤일수록 다음 노크가 더 선명하게 들린다.", priority: 0, condition: {}, choices: [
    { id: "patrol", label: "복도를 순찰한다", description: "연료 1을 사용해 Security를 높이고 위협을 낮춥니다.", requiredResources: { fuel: 1 }, effect: { resources: { fuel: -1, security: 2 }, hotelStats: { security: 2 }, threat: -2 } },
    { id: "rest", label: "모두 쉬게 한다", description: "투숙객들의 Stress가 조금 회복됩니다.", effect: { allGuestStress: -5 } },
  ] },
];
